[seagulls]
radius_ = 150
add_count = 15
angle_speed = 45.0
distance = 300
height_ = 20
circle_time = 1000
far_choice = 3
relax_time = 10000
scream_time = 60000
scream_file = "seagull"

[sharks]
count_ = 10
radius_ = 200
angle_speed = 10.0
distance = 800
circle_time = 1000
far_choice = 2

["fish schools"]
count_ = 30
radius_ = 100
angle_speed = 10.0
distance = 800
circle_time = 1000
far_choice = 2

[butterflies]
count_ = 30
radius_ = 250
