[candle]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 4.0
flicker = 0.1
flickerslow = 0.5
freq = 5.0
freqslow = 1.0
corona = "coronatrch.tga"
coronarange = 5.0
coronasize = 0.2

[candelabrum]
r = 0.0
g = 0.0
b = 0.0
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 10.0
flicker = 0.03
flickerslow = 0.2
freq = 5.0
freqslow = 1.0
corona = "coronachnd.tga"
coronarange = 15.0
coronasize = 0.4

[chandelier]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 1.0
att2 = 0.1
range = 40.0
flicker = 0.03
flickerslow = 0.1
freq = 5.0
freqslow = 1.0
corona = "coronachnd.tga"
coronarange = 50.0
coronasize = 2.2

[heater]
r = 1.5
g = 0.8
b = 0.3
att0 = 0.1
att1 = 0.7
att2 = 0.02
range = 40.0
flicker = 0.03
flickerslow = 0.4
freq = 15.0
freqslow = 0.4

[torchlight]
r = 1.2
g = 0.7
b = 0.4
att0 = 1.2
att1 = 1.0
att2 = 0.02
range = 40.0
flicker = 0.1
flickerslow = 0.5
freq = 15.0
freqslow = 1.0
corona = "coronatrch.tga"
coronarange = 40.0
coronasize = 0.2

[handtorchlight]
r = 2.2
g = 1.7
b = 1.4
att0 = 1.2
att1 = 1.0
att2 = 0.02
range = 40.0
flicker = 0.1
flickerslow = 0.5
freq = 15.0
freqslow = 1.0
corona = "coronatrch.tga"
coronarange = 40.0
coronasize = 0.2

[lamp]
r = 3.0
g = 1.5
b = 1.0
att0 = 0.2
att1 = 3.0
att2 = 0.05
range = 40.0
flicker = 0.19
flickerslow = 0.5
freq = 9.0
freqslow = 1.5
corona = "corona.tga"
coronarange = 40.0
coronasize = 1.0

[outside_day]
r = 0.3
g = 0.2
b = 0.1
att0 = 1.0
att1 = 0.0
att2 = 0.0
range = 10000.0
flicker = 0.0
flickerslow = 0.0
freq = 0.0
freqslow = 0.0

[outside_night]
r = 0.1
g = 0.2
b = 0.3
att0 = 1.0
att1 = 0.0
att2 = 0.0
range = 10000.0
flicker = 0.0
flickerslow = 0.0
freq = 0.0
freqslow = 0.0

[incas]
r = 3.0
g = 2.5
b = 1.0
att0 = 1.5
att1 = 0.5
att2 = 0.01
range = 30.0
flicker = 0.01
flickerslow = 0.04
freq = 10.0
freqslow = 0.1

[incasskyday]
r = 3.0
g = 2.5
b = 1.0
att0 = 1.5
att1 = 0.5
att2 = 0.01
range = 30.0
flicker = 0.0
flickerslow = 0.0
freq = 0.0
freqslow = 0.0

[incasskynight]
r = 3.0
g = 2.5
b = 1.0
att0 = 1.5
att1 = 0.5
att2 = 0.01
range = 30.0
flicker = 0.0
flickerslow = 0.0
freq = 0.0
freqslow = 0.0

[blueteleport]
r = 0.0
g = 2.5
b = 5.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = 0.14
flickerslow = 0.8
freq = 10.0
freqslow = 1.9
corona = "bluecorona.tga"
coronarange = 50.0
coronasize = 3.0

[redteleport]
r = 5.0
g = 1.0
b = 1.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = 0.14
flickerslow = 0.8
freq = 10.0
freqslow = 1.9
corona = "redcorona.tga"
coronarange = 50.0
coronasize = 3.0

[greenteleport]
r = 1.0
g = 5.0
b = 1.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = 0.14
flickerslow = 0.8
freq = 10.0
freqslow = 1.9
corona = "greencorona.tga"
coronarange = 50.0
coronasize = 3.0

[magsteleport]
r = 5.0
g = 1.0
b = 5.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = 0.14
flickerslow = 0.8
freq = 10.0
freqslow = 1.9
corona = "magcorona.tga"
coronarange = 50.0
coronasize = 3.0
