[candle]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 4.0
flicker = ["0.1\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.5\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["5.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronatrch.tga"
coronarange = ["5.0\t;Дистанция", "действия", "короны"]
coronasize = ["0.2\t;Размер", "короны"]

[candelabrum]
r = 0.0
g = 0.0
b = 0.0
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 10.0
flicker = ["0.03\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.2\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["5.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronachnd.tga"
coronarange = ["15.0\t;Дистанция", "действия", "короны"]
coronasize = ["0.4\t;Размер", "короны"]

[chandelier]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 1.0
att2 = 0.1
range = 40.0
flicker = ["0.03\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.1\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["5.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronachnd.tga"
coronarange = ["50.0\t;Дистанция", "действия", "короны"]
coronasize = ["2.2\t;Размер", "короны"]

[heater]
r = 1.5
g = 0.8
b = 0.3
att0 = 0.1
att1 = 0.7
att2 = 0.02
range = 40.0
flicker = ["0.03\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.4\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["15.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["0.4\t\t;Частота", "в", "гц", "для", "flickerSlow"]

[torchlight]
r = 1.2
g = 0.7
b = 0.4
att0 = 1.2
att1 = 1.0
att2 = 0.02
range = 40.0
flicker = ["0.1\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.5\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["15.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronatrch.tga"
coronarange = ["40.0\t;Дистанция", "действия", "короны"]
coronasize = ["0.2\t;Размер", "короны"]

[handtorchlight]
r = 2.2
g = 1.7
b = 1.4
att0 = 1.2
att1 = 1.0
att2 = 0.02
range = 40.0
flicker = ["0.1\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.5\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["15.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronatrch.tga"
coronarange = ["40.0\t;Дистанция", "действия", "короны"]
coronasize = ["0.2\t;Размер", "короны"]

[lamp]
r = 3.0
g = 1.5
b = 1.0
att0 = 0.2
att1 = 3.0
att2 = 0.05
range = 40.0
flicker = ["0.19\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.5\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["9.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.5\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "corona.tga"
coronarange = ["40.0\t;Дистанция", "действия", "короны"]
coronasize = ["1.0\t;Размер", "короны"]

[outside_day]
r = 0.3
g = 0.2
b = 0.1
att0 = 1.0
att1 = 0.0
att2 = 0.0
range = 10000.0
flicker = ["0.0\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.0\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["0.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["0.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]

[outside_night]
r = 0.1
g = 0.2
b = 0.3
att0 = 1.0
att1 = 0.0
att2 = 0.0
range = 10000.0
flicker = ["0.0\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.0\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["0.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["0.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]

[incas]
r = 3.0
g = 2.5
b = 1.0
att0 = 1.5
att1 = 0.5
att2 = 0.01
range = 30.0
flicker = ["0.01\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.04\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["10.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["0.1\t\t;Частота", "в", "гц", "для", "flickerSlow"]

[incasskyday]
r = 3.0
g = 2.5
b = 1.0
att0 = 1.5
att1 = 0.5
att2 = 0.01
range = 30.0
flicker = ["0.0\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.0\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["0.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["0.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]

[incasskynight]
r = 3.0
g = 2.5
b = 1.0
att0 = 1.5
att1 = 0.5
att2 = 0.01
range = 30.0
flicker = ["0.0\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.0\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["0.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["0.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]

[blueteleport]
r = 0.0
g = 2.5
b = 5.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = ["0.14\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.8\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["10.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.9\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "bluecorona.tga"
coronarange = ["50.0\t;Дистанция", "действия", "короны"]
coronasize = ["3.0\t;Размер", "короны"]

[redteleport]
r = 5.0
g = 1.0
b = 1.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = ["0.14\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.8\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["10.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.9\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "redcorona.tga"
coronarange = ["50.0\t;Дистанция", "действия", "короны"]
coronasize = ["3.0\t;Размер", "короны"]

[greenteleport]
r = 1.0
g = 5.0
b = 1.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = ["0.14\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.8\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["10.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.9\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "greencorona.tga"
coronarange = ["50.0\t;Дистанция", "действия", "короны"]
coronasize = ["3.0\t;Размер", "короны"]

[magsteleport]
r = 5.0
g = 1.0
b = 5.0
att0 = 0.1
att1 = 4.0
att2 = 0.2
range = 5.0
flicker = ["0.14\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.8\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["10.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.9\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "magcorona.tga"
coronarange = ["50.0\t;Дистанция", "действия", "короны"]
coronasize = ["3.0\t;Размер", "короны"]
