[smoke]
technique = "particles"
emissiontime = 350
windeffect = [0.0025, 0.0, 0.0, 1.0, 10000.0]
key_windeffect = [0, 0]
nonstopemit = 0
texture = "smoke9.tga"
particles_num = 32
lifetime = 10000
emitradius = 1.0
psize_max = 0.02
psize_min = 0.0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 20000.0]
speed = [1.0, 0.0, 0.0, 0.0, 0.0002, 500.0, 0.002, 3000.0]
key_alpha = [0.0, 0.0, 0.25, 2000.0, 0.0, 10000.0]
key_psize = [0, 0, 2, 3000, 4, 10000]

[smoke_inv]
technique = "particles_inv"
nonstopemit = 0
emissiontime = 500
texture = "smoke9.tga"
particles_num = 20
lifetime = 10000
emitradius = 1.0
psize_max = 0.02
psize_min = 0.0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 20000.0]
speed = [1.0, 0.0, 0.0, 0.0, 0.0002, 500.0, 0.002, 3000.0]
key_alpha = [0, 0, 1, 2000, 0, 10000]
key_psize = [0, 0, 3, 3000, 10, 20000]

[fire]
technique = "particlesfire"
uniformemit = 0
nonstopemit = 0
texture = "fire3.tga"
particles_num = 16
psize_max = 0.02
psize_min = 0.02
emitradius = 0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
lifetime = 1000
emissiontime = 50
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.00025, 2.0, 0.0]
speed = [1.0, 0.025, 0.0, 0.0, 0.0004, 500.0, 0.002, 3000.0]
key_alpha = [0, 0, 1, 100, 0, 1000]
key_psize = [0.0, 0.0, 2.0, 3000.0]

[fire_medium]
technique = "particles"
uniformemit = 0
nonstopemit = 0
emitdelta = 500
texture = "fire3.tga"
particles_num = 8
psize_max = 0.02
psize_min = 0.02
emitradius = 0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
lifetime = 4000
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.0005, 1.0, 0.0, 0.0, 1500.0]
speed = [1.0, 0.0, 0.0, 0.0, 0.0004, 500.0, 0.002, 3000.0]
key_alpha = [0, 0, 1, 500, 0, 4000]
key_psize = [0, 0, 6, 3000, 12, 20000]

[cancloud]
technique = "particles"
texture = "smoke9.tga"
particles_num = 4
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = 6000
weight = [-0.00025, 0.0005]
pscale = 1.0
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 10000.0]
speed = [0.2, 0.17, 0.2, 0.0, 0.01, 200.0, 0.0, 1000.0]
key_alpha = [1, 0, 0, 6000]
key_psize = [0.25, 0.0, 4.0, 200.0, 15.0, 6000.0]

[cancloud1]
technique = "particles"
texture = "smoke9.tga"
particles_num = 8
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = ["40000", "0", "40000", ";", "must", "be", "same", "as", "lifetime"]
weight = [-0.0001, 0.0005]
pscale = 0.1
spin = [0.0, 0.0025, 1.0, 0.0, 0.2, 10000.0]
speed = [0.01, 0.02, 4.0, 0.0, 1.1, 10.0, 0.12, 250.0, 0.112, 2000.0]
key_alpha = [0.6, 0.0, 0.5, 500.0, 0.25, 5000.0, 0.08, 20000.0]
key_psize = [0.25, 0.0, 2.6, 500.0, 10.0, 7000.0]

[cancloud2]
technique = "particles"
texture = "smoke_gray.tga"
particles_num = 8
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = ["40000", "0", "40000", ";", "must", "be", "same", "as", "lifetime"]
weight = [-0.0001, 0.0005]
pscale = 0.1
spin = [0.0, 0.0025, 1.0, 0.0, 0.2, 10000.0]
speed = [0.01, 0.02, 4.0, 0.0, 1.1, 10.0, 0.12, 250.0, 0.112, 2000.0]
key_alpha = [0.4, 0.0, 0.3, 5000.0, 0.15, 20000.0]
key_psize = [0.25, 0.0, 2.6, 500.0, 10.0, 7000.0]

[cancloud_fire]
technique = "particles"
texture = "smoke10.tga"
particles_num = 6
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = 200
weight = [-0.00025, 0.0005]
pscale = 1.5
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 10000.0]
speed = [0.15, 0.13, 0.1, 0.0, 0.01, 30.0, 0.0, 200.0]
key_alpha = [1, 0, 0, 200]
key_psize = [0.25, 0.0, 1.6, 200.0]

[cancloud_big]
technique = "particles"
texture = "smoke9.tga"
particles_num = 4
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = 6000
weight = [-0.00025, 0.0005]
pscale = 1.0
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 10000.0]
speed = [0.3, 0.25, 0.2, 0.0, 0.01, 200.0, 0.0, 1000.0]
key_alpha = [1, 0, 0, 6000]
key_psize = [0.25, 0.0, 6.0, 100.0, 20.0, 6000.0]

[cancloud_fire_big]
technique = "particles"
texture = "smoke10.tga"
particles_num = 8
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = 200
weight = [-0.00025, 0.0005]
pscale = 1.5
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 10000.0]
speed = [0.2, 0.17, 0.1, 0.0, 0.01, 30.0, 0.0, 200.0]
key_alpha = [1, 0, 0, 200]
key_psize = [0.25, 0.0, 2.4, 200.0]

[blast]
technique = "particles"
randomdirection = 0
texture = "smoke8.tga"
particles_num = 1
emitradius = 0
emitter_initime = 0
ddeviation = 0.1
gravity = 1.0
lifetime = 2000
weight = [0.0, 0.0]
pscale = 1.0
spin = [0.0, 0.0025, 0.5, 0.0, 0.0, 2000.0]
speed = [0.0, 0.0, 1.0, 0.0, 0.01, 150.0, 0.005, 1000.0]
key_alpha = [1, 0, 0, 2000]
key_psize = [2, 0, 8, 250, 24, 4000]

[blast_inv]
technique = "particles_inv"
randomdirection = 0
texture = "smoke9.tga"
particles_num = 4
emitradius = 0
emitter_initime = 0
ddeviation = 0.1
gravity = 1.0
lifetime = 4000
weight = [-0.00025, 0.0005]
pscale = 1.0
spin = [0.0, 0.0025, 0.5, 0.0, 0.0, 2000.0]
speed = [0.06, 0.06, 1.0, 0.0, 0.01, 150.0, 0.005, 1000.0]
key_alpha = [1, 0, 0, 4000]
key_psize = [1, 0, 10, 250, 20, 4000]

[watersplash]
technique = "particles"
double = 300
texture = "watersplash.tga"
particles_num = 16
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = 1500
weight = [-0.00025, 0.0005]
pscale = 1.0
spin = [0.0, 0.001, 1.0, 0.0, 0.0, 3000.0]
speed = [0.04, 0.01, 1.0, 0.0, 0.01, 100.0, 0.0, 700.0, -1.0, 3000.0]
key_alpha = [1, 0, 0, 3000]
key_psize = [0, 0, 2, 800, 2, 1000, 15, 3000]

[whitewater]
technique = "particles"
nonstopemit = 0
texture = "watersplash.tga"
emitdelta = 187
particles_num = 8
emitradius = 0.5
emitter_initime = 3000
ddeviation = 0.1
gravity = 1.0
lifetime = 2000
weight = [-0.00025, 0.0005]
pscale = 1.0
spin = [0.0, 0.001, 1.0, 0.0, 0.0, 3000.0]
speed = [0.025, 0.005, 1.0, 0.0, 0.01, 100.0, 0.0, 700.0, -1.0, 3000.0]
key_alpha = [1, 0, 1, 2000]
key_psize = [0, 0, 3, 800, 6, 3000]

[blast_smoke]
technique = "particles"
randomdirection = 0
texture = "smoke9.tga"
particles_num = 1
emitradius = 0.3
emitter_initime = 0
ddeviation = 0.1
gravity = 1.0
lifetime = 2000
weight = [0.0, 0.0]
pscale = 1.0
spin = [0.0, 0.0025, 0.5, 0.0, 0.0, 2000.0]
speed = [0.0, 0.0, 1.0, 0.0, 0.01, 150.0, 0.005, 1000.0]
key_alpha = [1, 0, 0, 2000]
key_psize = [1, 0, 3, 250, 9, 4000]

[waterfall]
technique = "particles"
nonstopemit = 0
texture = "smoke9.tga"
particles_num = 70
emitradius = 10.0
emissiontime = 100
ddeviation = 0.8
gravity = 1.0
lifetime = 3600
weight = 0.0052
windeffect = [0.0, 0.0, 0.0, 1.0, 1000.0]
pscale = 1.0
spin = 0.2
speed = [0.003, 0.001, 1.0, 0.0, 0.35, 1500.0]
key_alpha = [0.0, 0.0, 0.7, 600.0, 0.3, 1200.0, 0.6, 2400.0, 1.0, 3400.0, 0.0, 3600.0]
key_psize = [2.0, 0.0, 2.0, 300.0, 3.0, 3000.0]
key_angle = [-1.57, 0.0, 0.0, 300.0, 0.0, 1500.0, 1.0, 3000.0, -1.0, 3600.0]

[waterfall2]
technique = "particles"
nonstopemit = 0
texture = "watersplash2.tga"
particles_num = 32
emitradius = 0.5
emissiontime = 50
ddeviation = 0.1
gravity = 1.0
lifetime = 2000
weight = 0.0075
pscale = 1.0
spin = 0.0
speed = [0.025, 0.005, 0.35, 0.0, 0.2, 100.0, 0.1, 500.0, 0.0, 3000.0]
key_alpha = [1, 0, 0, 2000]
key_psize = [1, 0, 3, 800, 6, 3000]
key_angle = [-1.57, 0.0, 0.0, 300.0, 0.0, 1500.0]

[waterfall3]
technique = "particles"
nonstopemit = 0
texture = "smoke9.tga"
particles_num = 256
emitradius = 0.5
emissiontime = 50
ddeviation = 0.1
gravity = 1.0
lifetime = 700
weight = 0.001
windeffect = [0.0025, 0.0, 0.0, 0.0, 1000.0]
pscale = 1.0
spin = [0.0, 1.0, 0.0, 0.0, 3000.0]
speed = [0.025, 0.005, 0.35, 0.0]
key_alpha = [0.0, 0.0, 0.5, 50.0, 1.0, 100.0, 0.7, 600.0, 0.0, 700.0]
key_psize = [2, 0, 2, 500, 4, 700]
key_angle = [-1.57, 0.0, 0.0, 300.0, 0.0, 1500.0]

[fountain]
technique = "particles"
nonstopemit = 0
texture = "smoke9.tga"
particles_num = 150
emitradius = 0.5
emissiontime = 20
ddeviation = 0.1
gravity = 1.0
lifetime = 2000
weight = 0.005
windeffect = [0.0025, 0.0, 0.0, 1.0, 1000.0]
pscale = 0.05
spin = [0.0, 1.0, 0.0, 0.0, 3000.0]
speed = [0.05, 0.005, 0.35, 0.0, 0.2, 100.0, 0.1, 500.0, 0.0, 3000.0]
key_alpha = [1.0, 0.0, 0.5, 1000.0, 0.0, 2000.0]
key_psize = [0.3, 0.0, 0.75, 500.0, 0.0, 3000.0]
key_angle = [-1.57, 0.0, 0.0, 300.0, 0.0, 1500.0]

[sparkle_cloud]
color = 4294901760
technique = "particles"
surfaceoffset = 0.2
nonstopemit = 0
texture = "sparkle.tga"
particles_num = 256
emit_radius = 4.5
emissiontime = [20, 0]
ddeviation = 0.1
gravity = 1.0
lifetime = 1000
windeffect = [0.0025, 0.0, 0.0, 0.0, 1000.0]
pscale = 0.125
spin = [0.001, 2.0, 0.0]
speed = [0.0, 0.005]
key_alpha = [0.0, 0.0, 1.0, 50.0, 1.0, 300.0, 0.0, 1000.0]
key_psize = [0.0, 0.0, 1.0, 200.0, 0.0, 1000.0]

[sparkle_emitter]
technique = "particles"
nonstopemit = 0
texture = "sparkle.tga"
particles_num = 64
emissiontime = [10, 0]
ddeviation = 1.1
gravity = 1.0
lifetime = 1000
windeffect = [0.0025, 0.0, 0.0, 0.0, 1000.0]
pscale = 0.125
spin = [0.001, 2.0, 0.0]
speed = [0.01, 0.005, 1.0, 0.0, 0.0, 1000.0]
key_alpha = [0.0, 0.0, 1.0, 500.0]
key_psize = [0.0, 0.0, 0.5, 500.0, 0.0, 1000.0]

[geo]
randomnum = 2
file = ["particles\\palka01", "particles\\palka02", "particles\\palka03", "particles\\palka04", "particles\\palka05"]

[seafoam]
technique = "particles"
nonstopemit = 0
texture = "water1.tga"
particles_num = 300
emit_radius = 0.5
emissiontime = [50, 10]
ddeviation = 0.6
gravity = 1.0
lifetime = 700
weight = [0.00047, 0.0]
windeffect = 0.0
pscale = 5.5
spin = [-0.015, 0.0, 0.1, 0.0, 0.0, 5000.0]
speed = [0.0135, 0.01, 0.05, 0.0, 0.001, 7000.0]
key_alpha = [0.0, 0.0, 0.45, 100.0, 0.3, 500.0, 0.0, 700.0]
key_psize = [2.0, 0.0, 1.0, 4000.0]

[seafoam2]
technique = ["particles", "particles"]
nonstopemit = [0, 0]
texture = ["water1.tga", "water1.tga"]
particles_num = [500, 300]
emit_radius = [0.15, 0.25]
emissiontime = [50, 10, 50, 10]
ddeviation = [0.1, 0.5]
gravity = [0.0, 1.0]
lifetime = [4000, 700]
weight = [0.001, 0.0005, 0.00047, 0.0]
windeffect = [0.0, 0.0]
pscale = [6.0, 5.5]
spin = [0.04, 0.005, -0.1, 0.0, 0.0, 5000.0, 0.015, 0.0, 0.1, 0.0, 0.0, 5000.0]
speed = [0.1, 0.0, 0.05, 0.0, 0.001, 7000.0, 0.0135, 0.01, 0.05, 0.0, 0.001, 7000.0]
key_alpha = [1.0, 0.0, 0.0, 4000.0, 0.0, 0.0, 0.45, 100.0, 0.3, 500.0, 0.0, 700.0]
key_psize = [2.5, 0.0, 2.0, 10000.0, 2.0, 0.0, 1.0, 4000.0]

[seafoam_front]
technique = "particles"
nonstopemit = 0
texture = "sparcle2.tga"
particles_num = 200
emit_radius = 0.7
emissiontime = [25, 0]
ddeviation = 0.9
gravity = 0.04
lifetime = 1500
weight = [0.1, 0.02]
windeffect = 0.0
pscale = 10.0
spin = [0.005, 0.0, -0.1, 0.0, 0.0, 5000.0]
speed = [0.2, 0.0, 0.05, 0.0, 0.04, 1000.0, 0.01, 1300.0, 0.0, 1500.0]
key_alpha = [0.0, 0.0, 1.0, 50.0, 0.8, 900.0, 0.0, 1500.0]
key_psize = [4.5, 0.0, 60.0, 10000.0]

[ball_splash]
technique = "particles"
texture = "water1.tga"
particles_num = 20
emitradius = 0.0
emissiontime = 3
ddeviation = 0.01
gravity = 1.6
lifetime = 2000
weight = 0.005
windeffect = [0.0025, 0.0, 0.0, 1.0, 1000.0]
pscale = 0.05
spin = [0.0, 1.0, 0.0, 1.0, 3000.0]
speed = [0.08, 0.03, 0.35, 0.0, 0.2, 100.0, 0.05, 500.0, 0.0, 3000.0]
key_alpha = [0.65, 0.0, 0.4, 100.0, 0.2, 2000.0]
key_psize = [1.5, 0.0, 2.5, 500.0]

[sink]
technique = "particles"
texture = "water4.tga"
particles_num = 300
emitradius = 0.0
emissiontime = 1
ddeviation = 0.01
gravity = 0.1
lifetime = 1000
weight = 0.005
windeffect = [0.0025, 0.0, 0.0, 1.0, 1000.0]
pscale = 0.05
spin = [0.0, 1.0, 0.0, 1.0, 3000.0]
speed = [0.02, 0.005, 0.15, 0.0, 0.0, 500.0, -0.2, 1000.0]
key_alpha = [0.0, 0.0, 0.01, 500.0, 0.0, 1000.0]
key_psize = [0.9, 0.0, 0.8, 500.0]

[gunfire]
technique = "particles"
texture = "smoke9.tga"
particles_num = 8
emissiontime = 10
emitradius = 0
emitter_initime = 100
ddeviation = 0.1
gravity = 1.0
lifetime = 4000
weight = [-5e-05, 0.0005]
pscale = 0.1
spin = [0.0, 0.0025, 1.0, 0.0, 0.2, 10000.0]
speed = [0.01, 0.02, 2.0, 0.0, 0.1, 10.0, 0.01, 250.0, 0.001, 2000.0]
key_alpha = [1, 0, 0, 4000]
key_psize = [0.25, 0.0, 0.6, 250.0, 1.0, 2000.0]

[bomb_smoke]
inversecolor = 0
uniformemit = 0
nonstopemit = 0
emitdelta = 1
texture = "smoke9.tga"
technique = "Particles_Inv"
particles_num = 60
psize_max = 0.01
psize_min = 0.01
emitradius = 2.5
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
lifetime = 200
weight = [0.0, 0.0]
ptime = 0
pscale = 0.3
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 20000.0]
speed = [0.16, 0.08, 0.5, 0.0, 0.2, 150.0, 0.0, 1500.0]
key_alpha = [0.5, 0.0, 0.0, 150.0]
key_psize = [0.25, 0.0, 0.7, 50.0, 1.0, 150.0, 1.5, 550.0]

[candle]
technique = "particlesfire"
uniformemit = 0
nonstopemit = 0
texture = "candle64.tga"
particles_num = 16
psize_max = 0.02
psize_min = 0.02
emitradius = 0
chaosval = 0.0
gravity = 0.0
initial_speed = 0.0
lifetime = 500
emissiontime = 100
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.00015, 0.5, 0.0, 0.0, 1000.0]
speed = [1.0, 0.0, 0.0]
key_alpha = [0, 0, 1, 50, 1, 400, 0, 500]
key_psize = [0.0, 0.0, 0.2, 500.0]

[candle_mix]
frames_u = 2
frames_v = 2
frame_selection = 0
technique = "particles"
uniformemit = 0
nonstopemit = 0
texture = "candle_2x2.tga"
particles_num = 16
psize_max = 0.02
psize_min = 0.02
emitradius = 0
chaosval = 0.0
gravity = 0.0
initial_speed = 0.0
lifetime = 500
emissiontime = 100
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.00015, 0.5, 0.0, 0.0, 1000.0]
speed = [1.0, 0.0, 0.0]
key_alpha = [0, 0, 1, 50, 1, 400, 0, 500]
key_psize = [0.0, 0.0, 0.2, 500.0]

[torch]
frames_u = 2
frames_v = 1
frame_selection = 0
technique = "particlesfire"
uniformemit = 0
nonstopemit = 0
texture = "fire3.tga"
particles_num = 36
psize_max = 0.02
psize_min = 0.02
emitradius = 0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
lifetime = 1000
emissiontime = 25
weight = [0.0, 0.0]
ptime = 0
pscale = 2.0
spin = [0.0, 0.00025, 0.5, 0.0, 0.0, 1000.0]
speed = [1.0, 0.025, 0.0, 0.0, 0.0004, 500.0, 0.002, 3000.0]
key_alpha = [0, 0, 1, 100, 0, 1000]
key_psize = [0.0, 0.0, 0.7, 3000.0]

[fire_mix]
technique = "particles"
uniformemit = 0
nonstopemit = 0
texture = "fire3.tga"
particles_num = 16
psize_max = 0.02
psize_min = 0.02
emitradius = 0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
lifetime = 1000
emissiontime = 50
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.00025, 0.5, 0.0, 0.0, 1000.0]
speed = [1.0, 0.025, 0.0, 0.0, 0.0004, 500.0, 0.002, 3000.0]
key_alpha = [0, 0, 1, 100, 0, 1000]
key_psize = [0.0, 0.0, 2.0, 3000.0]

[waterfog]
technique = "particles"
nonstopemit = 0
emissiontime = 175
windeffect = [0.0025, 0.0, 0.0, 1.0, 10000.0]
texture = "smoke9.tga"
particles_num = 64
lifetime = 10000
emitradius = 2
psize_max = 0.02
psize_min = 0.0
ddeviation = 0.5
gravity = 0.0
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 10.0
spin = [1.0, 0.0025, 0.0, 0.0, 0.0, 20000.0]
speed = [0.6, 2.0, 0.0, 0.0, 0.0002, 500.0, 0.002, 3000.0]
key_alpha = [0.0, 0.0, 0.1, 2000.0, 0.0, 10000.0]
key_psize = [0, 0, 7, 3000, 5, 10000]

[waterfog_fall]
technique = "particles"
nonstopemit = [0, 0]
emissiontime = 350
windeffect = [0.0025, 0.0, 0.0, 1.0, 10000.0]
texture = "smoke9.tga"
particles_num = 60
lifetime = 10000
emitradius = 0.2
psize_max = 0.02
psize_min = 0.0
ddeviation = 0
gravity = 0.3
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 10.0
spin = ["0.0", "0.0025", "0", "0", "0.0", "20000speed", "=", "1.5", "0", "0.0", "0", "0.0002", "500", "0.002", "3000"]
key_alpha = [0.0, 0.0, 0.3, 9000.0, 0.0, 10000.0]
key_psize = [0, 0, 6, 8000, 12, 10000]
