[SAILS]
texturename = "parusall.tga"
texturecount = 4
texnumcommon = 0
texnumenglish = 1
texnumtreangle = 2
fssailwinddepend = 0.3
ftsailwinddepend = 0.1
flexspeed = 5e-06
maxsumwind = 0.001
fwindadding = 0.5
windvector_qnt = 200
windvector_tincr = 30
windvector_tadd = 8
windvector_sincr = 40
windvector_sadd = 10
windangldiscrete = 0.0001
maxturnangl = 0.6
turnstepangl = 0.002
rollingspeed = 0.0003
diffuse = [0.3, 0.3, 0.3, 0.3]
ambient = [1.5, 1.5, 1.5, 1.5]
specular = [0.0, 0.0, 0.0, 0.0]
emissive = [0.0, 0.0, 0.0, 0.0]
power = 0.5
fholedepend = 1.0
trianglewindspeed = [0.2, 0.6, 0.8]
trapecidalwindspeed = [0.4, 0.5, 0.6]
squarewindspeed = [0.4, 0.1, 0.6]
roll_z_val = 0.05
roll_z_delta = 0.01
roll_y_val = 0.06
roll_y_delta = 0.001
rollssailform = [0.2, 0.8, 1.0, 0.8, 0.4, 1.0, 1.3, 1.0, 0.4, 0.8, 1.0, 0.8, 0.2]
rolltsailform = [0.15, 0.5, 0.25, 0.8, 0.15]
tr_form_mul = 1.5
ftholeflexdepend = 0.02
fsholeflexdepend = 0.03
ffallssailaddmin = 0.1
ffallssailaddrand = 0.05
ffalltsailaddmin = 0.1
ffalltsailaddrand = 0.04

[FLAGS]
texturename = "flags\\flagall_ship_b.tga"
texturecountcolumn = 4
texturecountrow = 8
fseglen = 0.5
alfa_depend = 0.1
beta_depend = 0.15
alpha_rand = 0.1
beta_rand = 0.1
falfamax = 2.71
fbetamax = 2.95
falfastep = 0.2
fbetastep = 0.3
fwindam = 0.2
frotam = 0.3
fdownval = 0.07
fwindmaxvalue = 12.0

[ROPES]
texturename = "sail_rope.tga"
fseg_length = 2.0
fwidth = 0.04
fstay_width = 0.12
fend_length = 0.01
fwave = 0.7
fmaxch = 0.1
ftexheight = 0.2
fmaxdist = 200000.0
fdeepchangespeed = 0.1
frotatespeed = 0.05
fmindeepmul = 1.0
fvardeepmul = 0.7
frotateang = 0.5

[VANTS]
texturename = "vant.tga"
fwidth = 0.08
fropequant = 5
fhropexbeg = 0.5
fhropexend = 1.0
ftreangxbeg = 0.125
ftreangxend = 0.5
ftreangybeg = 0.0
ftreangyend = 0.9
fbalkybeg = 0.9
fbalkyend = 1.0
fvropexbeg = 0.0
fvropexend = 0.125
ftreangwidth = 0.7
ftreangheight = 0.8
fvropeheight = 1.0
fhropeheight = 1.0
fbalkheight = 0.05
fbalkwidth = 1.2
fdiscrvalue = 0.01
fdisapearvalue = 5.0
fvantmaxdist = 250000

[VANTS_L]
texturename = "vanx.tga"
fwidth = 0.06
fropequant = 3
fhropexbeg = 0.5
fhropexend = 1.0
ftreangxbeg = 0.125
ftreangxend = 0.5
ftreangybeg = 0.0
ftreangyend = 0.9
fbalkybeg = 0.9
fbalkyend = 1.0
fvropexbeg = 0.0
fvropexend = 0.125
ftreangwidth = 0.3
ftreangheight = 0.4
fvropeheight = 0.7
fhropeheight = 0.7
fbalkheight = 0.05
fbalkwidth = 1.2
fdiscrvalue = 0.01
fdisapearvalue = 5.0
fvantmaxdist = 250000

[VANTS_Z]
texturename = "vanz.tga"
fwidth = 0.05
fropequant = 2
fhropexbeg = 0.5
fhropexend = 1.0
ftreangxbeg = 0.125
ftreangxend = 0.5
ftreangybeg = 0.0
ftreangyend = 0.9
fbalkybeg = 0.9
fbalkyend = 1.0
fvropexbeg = 0.0
fvropexend = 0.125
ftreangwidth = 0.15
ftreangheight = 0.3
fvropeheight = 0.7
fhropeheight = 0.7
fbalkheight = 0.05
fbalkwidth = 1.2
fdiscrvalue = 0.01
fdisapearvalue = 5.0
fvantmaxdist = 250000
