[default]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 32.0
flicker = ["0.1\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.5\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["15.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronatrch.tga"
coronarange = ["5.0\t;Дистанция", "действия", "короны"]
coronasize = ["0.2\t;Размер", "короны"]
coronatechnique = "coronas"

[cannon]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 32.0
flicker = ["0.1\t\t;Малая", "амплитуда", "без", "интерполяции", "(max", "1.0)"]
flickerslow = ["0.5\t;Большая", "амплитуда", "с", "линейной", "интерполяцией", "(max", "1.0)"]
freq = ["15.0\t\t;Частота", "в", "гц", "для", "flicker"]
freqslow = ["1.0\t\t;Частота", "в", "гц", "для", "flickerSlow"]
corona = "coronatrch.tga"
coronarange = ["5.0\t;Дистанция", "действия", "короны"]
coronasize = ["0.2\t;Размер", "короны"]
coronatechnique = "coronas"
