[default]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 32.0
flicker = 0.1
flickerslow = 0.5
freq = 15.0
freqslow = 1.0
corona = "coronatrch.tga"
coronarange = 5.0
coronasize = 0.2
coronatechnique = "coronas"

[cannon]
r = 1.2
g = 0.7
b = 0.4
att0 = 0.1
att1 = 3.0
att2 = 0.3
range = 32.0
flicker = 0.1
flickerslow = 0.5
freq = 15.0
freqslow = 1.0
corona = "coronatrch.tga"
coronarange = 5.0
coronasize = 0.2
coronatechnique = "coronas"
