[mainmenu_day]
ch_loop = ["water_menu", "18", "19", "0.4", "day_wind", "1", "1", "0.2"]
ch = ["seagull", "5", "20", "0.1"]

[mainmenu_day_rain]
ch_loop = ["land_rain", "1", "1", "0.5", "water_menu", "1", "1", "0.3", "storm_wind", "1", "1", "0.2"]
ch = ["seagull", "5", "20", "0.1"]

[mainmenu_night]
ch_loop = ["water_menu", "1", "1", "0.3", "cricket_night", "9", "1", "0.3", "day_wind", "1", "1", "0.2"]

[mainmenu_night_rain]
ch_loop = ["water_menu", "1", "1", "0.5", "land_rain", "1", "1", "0.9", "storm_wind", "1", "1", "0.4"]

[land_day]
ch_loop = ["day_wind", "1", "1", "0.3", "birds", "1", "1", "1.0", "cricket", "8", "8", "0.2"]
ch = ["popugay", "25", "70", "0.1", "solovey", "5", "20", "0.2", "monkey", "25", "70", "0.1", "cricket_02", "25", "70", "0.1", "seagull", "5", "20", "0.1"]

[land_day_rain]
ch_loop = ["land_rain", "1", "1", "0.5", "day_wind", "1", "1", "0.5"]
ch = ["seagull", "5", "20", "0.1"]

[land_day_storm]
ch_loop = ["storm_land_rain", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]
ch = ["seagull", "5", "20", "0.1"]

[land_night]
ch_loop = ["night_wind", "1", "1", "0.5", "cricket_night", "9", "10", "0.1"]
ch = ["animals_night", "10", "30", "0.3", "bird_night", "5", "15", "0.5", "monkey", "25", "70", "0.1", "cricket_night_02", "25", "70", "0.3", "seagull", "5", "20", "0.1"]

[land_night_rain]
ch_loop = ["night_wind", "1", "1", "0.5", "weather\\strong_rain1.wav", "1", "1", "0.6"]
ch = ["bird_night", "25", "45", "0.2", "solovey", "25", "40", "0.05", "animals_night", "10", "30", "0.3", "seagull", "5", "20", "0.1"]

[land_night_storm]
ch_loop = ["storm_land_rain", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]
ch = ["seagull", "5", "20", "0.1"]

[sea_day]
ch_loop = ["day_wind", "1", "1", "0.5"]

[sea_day_rain]
ch_loop = ["sea_rain", "1", "1", "0.5", "day_wind", "1", "1", "0.5"]

[sea_day_storm]
ch_loop = ["storm_wind", "1", "1", "0.2", "storm_sea_water", "1", "1", "0.3", "storm_sea_rain", "1", "1", "0.3"]

[sea_night]
ch_loop = ["night_wind", "1", "1", "0.5"]

[sea_night_rain]
ch_loop = ["storm_sea_rain", "1", "1", "0.5"]

[sea_night_storm]
ch_loop = ["storm_wind", "1", "1", "0.2", "storm_sea_water", "1", "1", "0.3", "storm_sea_rain", "1", "1", "0.3"]

[seashore_day]
ch = ["seagull", "10", "10", "0.3", "day_wind", "1", "1", "0.3", "cricket", "25", "70", "0.2", "cricket_02", "25", "70", "0.1"]

[seashore_day_rain]
ch = ["seagull", "8", "20", "0.3", "sea_rain", "1", "1", "0.5", "day_wind", "1", "1", "0.5"]

[seashore_day_storm]
ch = ["seagull", "10", "10", "0.3", "storm_wind", "1", "1", "0.2", "storm_sea_water", "1", "1", "0.3", "storm_sea_rain", "1", "1", "0.3"]

[seashore_night]
ch_loop = ["night_wind", "1", "1", "0.5", "cricket_night", "9", "10", "0.1"]
ch = ["animals_night", "10", "30", "0.3", "seagull", "10", "10", "0.3"]

[seashore_night_rain]
ch_loop = ["night_wind", "1", "1", "0.5", "weather\\strong_rain1.wav", "1", "1", "0.6"]
ch = ["bird_night", "25", "45", "0.2", "animals_night", "10", "30", "0.3", "seagull", "8", "20", "0.3"]

[seashore_night_storm]
ch_loop = ["storm_land_rain", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]
ch = ["seagull", "8", "20", "0.3"]

[cave]
ch = ["AMBIENT\\cave\\quickpatt.wav", "60", "120", "0.8", "rat", "3", "30", "0.6", "drop_cave", "5", "15", "0.75"]

[dungeon]
ch = ["AMBIENT\\cave\\quickpatt.wav", "60", "120", "0.8", "rat", "3", "30", "0.6"]

[town_day]
ch_loop = ["day_wind", "1", "1", "0.1", "cricket", "8", "8", "0.3", "AMBIENT\\people_talk.wav", "1", "1", "0.07"]
ch = ["popugay", "25", "70", "0.1", "solovey", "25", "70", "0.2", "monkey", "25", "70", "0.1", "cricket_02", "25", "70", "0.1", "rat", "40", "90", "0.5", "dog", "35", "70", "0.2", "door", "40", "130", "0.3", "cough", "25", "70", "0.2", "AMBIENT\\towns\\telega.wav", "60", "120", "0.3"]

[town_night]
ch_loop = ["day_wind", "1", "1", "0.05", "cricket_night", "9", "10", "0.1"]
ch = ["animals_night", "25", "70", "0.3", "cricket_night_02", "25", "70", "0.3", "bird_night", "25", "70", "0.3", "dog", "50", "130", "0.2"]

[town_day_rain]
ch_loop = ["day_wind", "1", "1", "0.5", "land_rain", "1", "1", "0.5", "AMBIENT\\people_talk.wav", "1", "1", "0.10"]
ch = ["dog", "35", "70", "0.3", "door", "40", "130", "0.3"]

[town_day_storm]
ch_loop = ["AMBIENT\\people_talk.wav", "1", "1", "0.02", "storm_land_rain", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]
ch = ["dog", "35", "70", "0.3"]

[town_night_rain]
ch_loop = ["day_wind", "1", "1", "0.5", "land_rain", "1", "1", "0.3", "weather\\easy_rain1.wav", "1", "1", "0.6", "AMBIENT\\people_talk.wav", "1", "1", "0.10"]
ch = ["dog", "35", "70", "0.3"]

[town_night_storm]
ch_loop = ["storm_land_rain", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]
ch = ["dog", "35", "70", "0.3"]

[shop]
ch = ["coins", "5", "15", "0.65", "noise", "5", "15", "0.65", "noise", "5", "15", "0.65", "AMBIENT\\SHOP\\paper.wav", "2", "10", "0.55", "sigh", "20", "150", "0.4"]

[shipyard]
ch_loop = ["AMBIENT\\SHIPYARD\\Fon_In_01.wav", "1", "1", "0.3"]

[church]
ch = ["church_inside", "60", "120", "0.1", "AMBIENT\\church\\zvon.wav", "40", "5", "0.5"]

[tavern]
ch_loop = ["AMBIENT\\TAVERN\\Tavern_In_Fon_01.WAV", "1", "1", "2.0"]
ch = ["AMBIENT\\pirates.WAV", "20", "10", "0.2", "drop_tavern", "20", "10", "0.1", "man_tavern", "30", "20", "0.1", "man_tavern", "30", "35", "0.1", "man_tavern", "50", "27", "0.1", "talks_tavern", "20", "70", "0.1", "talks_tavern", "20", "70", "0.1", "otr_tavern", "70", "120", "0.1", "otr_tavern", "70", "120", "0.1", "otr_tavern", "70", "120", "0.1", "money", "40", "120", "0.1", "fill_up", "40", "70", "0.1", "fill_up", "40", "70", "0.1"]

[residence]
ch = ["AMBIENT\\SHOP\\paper.wav", "2", "10", "0.55", "AMBIENT\\SHOP\\paper.wav", "2", "10", "0.55", "dog", "100", "200", "0.25", "AMBIENT\\TOWNS\\telega.wav", "4", "20", "0.2", "sigh", "10", "60", "0.35", "sigh", "10", "60", "0.35"]

[deck_fight]
ch = ["grapes2bort", "1", "50", "0.45", "zalp", "2", "7", "0.45", "svist_shrapneli", "1", "7", "0.6", "episode_boom", "5", "30", "0.45", "fly_ball", "1", "7", "0.45", "fort_cann_explode", "2", "10", "0.45", "cannon_fire", "2", "10", "0.45"]

[fort_attack]
ch = ["zalp", "2", "5", "0.45", "svist_shrapneli", "1", "5", "0.6", "episode_boom", "10", "40", "0.45", "fly_ball", "3", "15", "0.45", "fort_cannon_fire", "2", "10", "0.45"]

[deck]
ch = ["seagull", "5", "10", "0.3"]

[slave_deck]
ch_loop = ["storm_land_rain", "1", "1", "0.5", "storm_sea_water", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]

[incquisitio]
ch = ["cough", "10", "60", "0.35", "cough", "10", "60", "0.35", "AMBIENT\\JAIL\\jail_door1.wav", "10", "60", "0.65", "AMBIENT\\JAIL\\jail_door2.wav", "10", "60", "0.65", "AMBIENT\\JAIL\\sniff.wav", "5", "25", "0.55", "AMBIENT\\JAIL\\chain.wav", "40", "65", "0.58", "AMBIENT\\JAIL\\shackles.wav", "30", "70", "0.45", "AMBIENT\\JAIL\\sniff.wav", "30", "70", "0.45", "AMBIENT\\JAIL\\sniff.wav", "30", "70", "0.45"]

[jail]
ch = ["cough", "10", "60", "0.35", "cough", "10", "60", "0.35", "AMBIENT\\JAIL\\jail_door1.wav", "10", "60", "0.65", "AMBIENT\\JAIL\\jail_door2.wav", "10", "60", "0.65", "AMBIENT\\JAIL\\sniff.wav", "5", "25", "0.55", "AMBIENT\\JAIL\\sigh.wav", "5", "15", "0.85", "AMBIENT\\JAIL\\sigh2.wav", "5", "15", "0.85", "drop_cave", "5", "15", "0.75", "drop_cave", "5", "15", "0.75", "AMBIENT\\JAIL\\chain.wav", "40", "65", "0.58", "AMBIENT\\JAIL\\shackles.wav", "30", "70", "0.45", "rat", "3", "30", "0.6"]

[house]
ch = ["AMBIENT\\TOWNS\\telega.wav", "4", "20", "0.3", "dog", "100", "200", "0.25", "AMBIENT\\TOWNS\\telega.wav", "4", "20", "0.2", "dog", "10", "20", "0.3", "noise", "2", "15", "0.2", "noise", "2", "15", "0.2"]

[LostShipsCity_day]
ch = ["seagull", "10", "10", "0.3", "water_menu", "1", "1", "0.1", "day_wind", "1", "1", "0.3", "squeak_LSC", "3", "10", "0.3"]

[LostShipsCity_day_rain]
ch = ["seagull", "8", "20", "0.3", "sea_rain", "1", "1", "0.5", "day_wind", "1", "1", "0.5", "squeak_LSC", "3", "10", "0.3"]

[LostShipsCity_day_storm]
ch = ["seagull", "10", "10", "0.3", "storm_wind", "1", "1", "0.2", "storm_sea_water", "1", "1", "0.3", "storm_sea_rain", "1", "1", "0.3", "storm_land_rain", "1", "1", "0.5", "squeak_LSC_storm", "5", "5", "0.4"]

[LostShipsCity_night]
ch_loop = ["night_wind", "1", "1", "0.5", "water_menu", "1", "1", "0.2"]
ch = ["seagull", "10", "10", "0.3", "squeak_LSC", "3", "10", "0.3"]

[LostShipsCity_night_rain]
ch_loop = ["night_wind", "1", "1", "0.5", "strong_rain", "1", "1", "0.6"]
ch = ["seagull", "8", "20", "0.3", "squeak_LSC", "3", "10", "0.3"]

[LostShipsCity_night_storm]
ch_loop = ["storm_sea_water", "1", "1", "0.3", "storm_sea_rain", "1", "1", "0.3", "storm_land_rain", "1", "1", "0.5", "storm_wind", "1", "1", "0.5"]
ch = ["seagull", "8", "20", "0.3", "squeak_LSC_storm", "5", "5", "0.4"]

[LSC_inside_day]
ch_loop = ["day_wind2", "1", "1", "0.3"]
ch = ["squeak_LSC_inside", "3", "10", "0.1"]

[LSC_inside_day_rain]
ch_loop = ["sea_rain2", "1", "1", "0.5", "day_wind2", "1", "1", "0.5"]
ch = ["squeak_LSC_inside", "3", "10", "0.1"]

[LSC_inside_day_storm]
ch_loop = ["storm_wind2", "1", "1", "0.2", "storm_sea_water2", "1", "1", "0.3", "storm_sea_rain2", "1", "1", "0.3", "storm_land_rain2", "1", "1", "0.5"]
ch = ["squeak_LSC_storm_inside", "4", "8", "0.1"]

[LSC_inside_night]
ch_loop = ["night_wind2", "1", "1", "0.5"]
ch = ["squeak_LSC_inside", "3", "10", "0.1"]

[LSC_inside_night_rain]
ch_loop = ["night_wind2", "1", "1", "0.5", "strong_rain2", "1", "1", "0.6"]
ch = ["squeak_LSC_inside", "3", "10", "0.1"]

[LSC_inside_night_storm]
ch_loop = ["storm_sea_water2", "1", "1", "0.3", "storm_sea_rain2", "1", "1", "0.3", "storm_land_rain2", "1", "1", "0.5", "storm_wind2", "1", "1", "0.5"]
ch = ["squeak_LSC_storm_inside", "4", "8", "0.1"]

[underwater]
ch_loop = ["underwater_al", "1", "1", "1.3"]

[teno_inside]
ch = ["AMBIENT\\teno_inside\\evil1.wav", "10", "60", "0.5", "AMBIENT\\teno_inside\\patter.wav", "3", "20", "0.31", "AMBIENT\\teno_inside\\patter.wav", "3", "20", "0.5", "AMBIENT\\teno_inside\\quickpatters.wav", "40", "95", "0.52", "AMBIENT\\teno_inside\\wind.wav", "10", "11", "1.0", "AMBIENT\\teno_inside\\big_ring.wav", "35", "85", "0.45"]

[reef]
ch_loop = ["animals_night", "1", "1", "0.3"]
ch = ["Reef\\reef_01.wav", "4", "20", "0.2", "Reef\\reef_02.wav", "4", "20", "0.2", "Reef\\reef_03.wav", "4", "20", "0.2", "AMBIENT\\Horror\\horror1.wav", "4", "20", "0.2", "AMBIENT\\LAND\\bird_night_001.wav", "4", "20", "0.2", "AMBIENT\\LAND\\bird_night_002.wav", "4", "20", "0.2", "AMBIENT\\LAND\\bird_night_003.wav", "4", "20", "0.2", "AMBIENT\\LAND\\bird_night_004.wav", "4", "20", "0.2", "AMBIENT\\LAND\\bird_night_005.wav", "4", "20", "0.2", "AMBIENT\\LAND\\bird_night_006.wav", "4", "20", "0.2", "Types\\skel.wav", "4", "20", "0.2", "Types\\skel.wav", "4", "20", "0.2", "Types\\skel.wav", "4", "20", "0.2", "Types\\skel.wav", "4", "20", "0.2", "Types\\warrior05.wav", "4", "20", "0.2", "Types\\warrior05.wav", "4", "20", "0.2", "AMBIENT\\LAND\\obezyna_001.wav", "4", "20", "0.2", "AMBIENT\\LAND\\obezyna_002.wav", "4", "20", "0.2", "AMBIENT\\LAND\\obezyna_003.wav", "4", "20", "0.2", "AMBIENT\\LAND\\obezyna_004.wav", "4", "20", "0.2", "AMBIENT\\LAND\\obezyna_005.wav", "4", "20", "0.2", "AMBIENT\\teno_inside\\evil1.wav", "10", "60", "0.5", "AMBIENT\\teno_inside\\evil1.wav", "10", "60", "0.5", "AMBIENT\\teno_inside\\evil1.wav", "10", "60", "0.5", "People", "Fight\\Peace_woman_death_05.wav", "10", "60", "0.5", "People", "Fight\\Peace_woman_death_03.wav", "10", "60", "0.5"]

[mine]
ch = ["AMBIENT\\cave\\quickpatt.wav", "60", "120", "0.8", "rat", "3", "30", "0.6", "drop_cave", "5", "15", "0.75", "Sea", "Battles\\udar_metal_001.wav", "4", "20", "0.2", "Sea", "Battles\\udar_metal_001.wav", "4", "20", "0.2", "Sea", "Battles\\udar_metal_002.wav", "4", "20", "0.2", "Sea", "Battles\\udar_metal_002.wav", "4", "20", "0.2", "Sea", "Battles\\udar_metal_003.wav", "4", "20", "0.2", "Sea", "Battles\\udar_metal_003.wav", "4", "20", "0.2", "Sea", "Battles\\vedro_002.wav", "4", "20", "0.2"]
