[MAIN]
item = ["VIDEO", "VIDEOBASE", "100", "pc", "BUTTON", "EXIT_BTN", "199", "FORMATEDTEXT", "INFO_TEXT"]

[EXIT_BTN]
position = [777, 0, 799, 22]
group = "ICONS_SPEC"
picture = ["exit", "button"]
command = ["click", "event:exitCancel"]
shadowcolor = [0, 0, 0, 0]

[LOGO]
position = [223, 1, 575, 89]
texturename = "interfaces\\SL_Logo.tga"

[INFO_TEXT]
position = [26, -30, 774, 603]
fontscale = 1.6
linespace = 1
font = "interface_button"
alignment = "center"
