[MAIN]
item = ["VIDEO", "VIDEOBASE", "TITLE", "TITLE", "100", "pc", "BUTTON", "EXIT_BTN", "TEXTBUTTON2", "NoEatNoRats", "TEXTBUTTON2", "QuestLogShow", "TEXTBUTTON2", "TestRansackCaptain", "TEXTBUTTON2", "LocatorShow", "TEXTBUTTON2", "ExpLogShow", "TEXTBUTTON2", "PGGLogShow", "TEXTBUTTON2", "CameraEnableFree", "TEXTBUTTON2", "WorldAlivePause", "TEXTBUTTON2", "BETTAMODE"]

[EXIT_BTN]
position = [775, 7, 797, 29]
group = "ICONS_SPEC"
picture = ["exit", "button"]
command = ["click", "event:exitCancel"]
shadowcolor = [0, 0, 0, 0]

[NoEatNoRats]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 70, 550, 105]
string = "NoEat_NoRats"

[QuestLogShow]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 125, 550, 160]
string = "QuestLogShow"

[TestRansackCaptain]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 180, 550, 215]
string = "TestRansackCaptain"

[LocatorShow]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 235, 550, 270]
string = "LocatorShow"

[ExpLogShow]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 290, 550, 325]
string = "ExpLogShow"

[PGGLogShow]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 345, 550, 380]
string = "PGGLogShow"

[CameraEnableFree]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 400, 550, 435]
string = "locCameraEnableFree"

[WorldAlivePause]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 455, 550, 490]
string = "WorldAlivePause"

[BETTAMODE]
bnotuse = 1
command = ["deactivate", "event:exitCancel", "click", "activate"]
position = [220, 510, 550, 545]
string = "BettaTest"
