[MAIN]
item = ["PICTURE", "MAIN_BACK", "TITLE", "TITLE", "100", "pc", "BUTTON", "EXIT_BTN", "400", "PICTURE", "CHARACTER_BIG_PICTURE", "STATUSLINE", "LOYALITY", "505", "FORMATEDTEXT", "LOYALITY_STR", "505", "FORMATEDTEXT", "REPUTATION_STR", "400", "IMAGECOLLECTION", "SUBSTRATE", "400", "IMAGECOLLECTION", "CHARACTER_BIG_PICTURE_BORDER", "200", "TABLE", "TABLE_SPECIAL", "200", "TABLE", "TABLE_SKILL_1", "200", "TABLE", "TABLE_SKILL_2", "200", "TABLE", "TABLE_PERKS", "200", "TABLE", "TABLE_OTHER", "201", "SCROLLER", "SCROLL_PERKS", "504", "FORMATEDTEXT", "HERO_NAME", "504", "FORMATEDTEXT", "STR_1", "504", "FORMATEDTEXT", "STR_2", "504", "FORMATEDTEXT", "STR_3", "504", "FORMATEDTEXT", "STR_4", "120", "PICTURE", "TABBTN_1", "125", "FORMATEDTEXT", "TABSTR_1", "120", "PICTURE", "TABBTN_2", "125", "FORMATEDTEXT", "TABSTR_2", "505", "STATUSLINE", "BAR_HEALTH", "505", "BUTTON", "B_SKILLUP", "505", "BUTTON", "B_SKILLDOWN", "555", "FORMATEDTEXT", "FREE_SKILL", "555", "FORMATEDTEXT", "FREE_SPECIAL", "555", "TEXTBUTTON2", "GAME_ACCEPT", "555", "TEXTBUTTON2", "GAME_CANCEL", "WINDOW", "MAIN_WINDOW", "555", "RECTANGLE", "PERK_FADER", "555", "FRAME", "PERK_WINDOW_FRAME", "555", "TEXTBUTTON2", "PERK_ACCEPT", "555", "TEXTBUTTON2", "PERK_CANCEL", "555", "FORMATEDTEXT", "PERK_WINDOW_CAPTION", "555", "FORMATEDTEXT", "PERK_WINDOW_TEXT", "555", "FORMATEDTEXT", "PERK_TEXT_FREE", "555", "pc", "BUTTON", "PERK_EXIT_BTN", "555", "PICTURE", "PERK_PICTURE", "556", "PICTURE", "PERK_ON", "555", "TABLE", "PERK_TABLE_NEED", "WINDOW", "PERK_WINDOW", "555", "RECTANGLE", "MSG_FADER", "555", "FRAME", "MSG_WINDOW_FRAME", "555", "TEXTBUTTON2", "MSG_OK", "555", "FORMATEDTEXT", "MSG_WINDOW_CAPTION", "555", "FORMATEDTEXT", "MSG_WINDOW_TEXT", "555", "pc", "BUTTON", "MSG_EXIT_BTN", "WINDOW", "MSG_WINDOW"]

[PERK_WINDOW]
show = 0
nodelist = ["PERK_FADER", "PERK_ACCEPT", "PERK_CANCEL", "PERK_WINDOW_FRAME", "PERK_WINDOW_CAPTION", "PERK_WINDOW_TEXT", "PERK_EXIT_BTN", "PERK_PICTURE", "PERK_ON", "PERK_TABLE_NEED", "PERK_TEXT_FREE"]

[PERK_TABLE_NEED]
command = ["click", "select:PERK_TABLE_NEED", "deactivate", "event:ExitPerkMenu", "rclick", "select:PERK_TABLE_NEED", "event:ShowInfoWindow", "upstep", "downstep"]
position = [187, 310, 317, 405]
vlinewidth = 0
hlineheight = 1
rowquantity = 4
colquantity = 2
fontcellvalignment = "center"
fontcellalignment = "center"
selectimage = ["color=(0", "128", "48", "48)"]
colswidth = [27, 102]
rowsheight = [1, 30, 30, 30]
normallineheight = 28
fontlist1 = "INTERFACE_TITLE"

[PERK_ON]
position = [196, 193, 304, 301]
texturename = "interfaces\\usedflag.tga"

[PERK_PICTURE]
position = [196, 193, 304, 301]
texturename = "interfaces\\portraits\\256\\face_1.tga"

[PERK_WINDOW_CAPTION]
command = "click"
babsoluterectangle = 5
position = [247, 162, 555, 194]
font = ["interface_button", "1.0"]
linespace = 10
alignment = "center"
color = [255, 255, 255, 255]
backoffset = [1, 2, 0, -2]
string = "Abilities"

[PERK_TEXT_FREE]
command = "click"
position = [310, 383, 618, 415]
fontscale = 1.0
linespace = 20
alignment = "center"

[PERK_WINDOW_TEXT]
command = "click"
position = [298, 197, 625, 382]
fontscale = 0.9
linespace = 18
alignment = ["center", "1"]
color = [255, 255, 255, 255]

[PERK_FADER]
babsoluterectangle = 5
position = [0, 0, 800, 600]
leftcolor = [150, 0, 0, 0]
topcolor = [150, 0, 0, 0]
rightcolor = [150, 0, 0, 0]
bottomcolor = [150, 0, 0, 0]
bordercolor = [0, 0, 0, 0]

[PERK_ACCEPT]
bbreakcommand = 1
command = ["activate", "click", "event:AcceptPerk", "deactivate", "event:ExitPerkMenu"]
position = [210, 412, 400, 444]
string = "Accept"
glowoffset = [0, 0]

[PERK_CANCEL]
bbreakcommand = 1
command = ["activate", "click", "event:ExitPerkMenu", "deactivate", "event:ExitPerkMenu"]
position = [405, 412, 590, 444]
string = "Cancel"
glowoffset = [0, 0]

[PERK_WINDOW_FRAME]
position = [179, 156, 624, 452]
captionheight = 28
captionimage = ["piclist=SKILLS", "picname=SKILLBORDER", "color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4

[PERK_EXIT_BTN]
position = [596, 161, 618, 183]
group = "ICONS_SPEC"
picture = ["exit", "button"]
command = ["click", "event:ExitPerkMenu"]
shadowcolor = [0, 0, 0, 0]

[MAIN_WINDOW]
show = 1
nodelist = ["CHARACTER_BIG_PICTURE", "HERO_NAME", "STR_1", "STR_2", "STR_3", "STR_4", "TABBTN_1", "TABSTR_1", "TABBTN_2", "TABSTR_2", "LOYALITY_STR", "LOYALITY", "REPUTATION_STR", "SUBSTRATE", "CHARACTER_BIG_PICTURE_BORDER", "SCROLL_PERKS", "BAR_HEALTH", "FREE_SKILL", "FREE_SPECIAL", "TABLE_SPECIAL", "TABLE_SKILL_1", "TABLE_SKILL_2", "TABLE_PERKS", "TABLE_OTHER", "TABSTR_1", "TABSTR_2", "B_SKILLUP", "B_SKILLDOWN"]

[GAME_ACCEPT]
bbreakcommand = 1
command = ["activate", "click", "event:exitCancel", "deactivate", "event:exitCancel"]
position = [282, 572, 392, 597]
string = "Ok"
fontscale = 0.8
glowoffset = [0, 0]

[GAME_CANCEL]
bbreakcommand = 1
command = ["activate", "click", "event:exitCancel", "deactivate", "event:exitCancel"]
position = [416, 572, 526, 597]
string = "Cancel"
fontscale = 0.8
glowoffset = [0, 0]

[B_SKILLUP]
group = "ICONS"
bbreakcommand = 1
command = ["click", "rclick"]
position = [572, 45, 602, 73]
picture = ["right", "arrow"]

[B_SKILLDOWN]
group = "ICONS"
bbreakcommand = 1
command = ["click", "rclick"]
position = [542, 45, 572, 73]
picture = ["left", "arrow"]

[MAIN_BACK]
babsoluterectangle = 5
position = [0, 0, 800, 600]
texturename = "interfaces\\card_desk.tga"

[EXIT_BTN]
position = [775, 14, 797, 36]
group = "ICONS_SPEC"
picture = ["exit", "button"]
command = ["click", "event:exitCancel"]
shadowcolor = [0, 0, 0, 0]

[TITLE]
position = [0, 10, 800, 42]

[CHARACTER_BIG_PICTURE]
position = [299, 85, 509, 295]
texturename = "interfaces\\portraits\\256\\face_1.tga"

[TABLE_SPECIAL]
command = ["click", "select:TABLE_SPECIAL", "rclick", "select:TABLE_SPECIAL", "event:ShowInfoWindow", "deactivate", "event:exitCancel", "upstep", "downstep"]
position = [89, 58, 288, 311]
vlinewidth = 0
hlineheight = 2
rowquantity = 8
colquantity = 4
fontcellvalignment = "center"
fontcellalignment = "left"
selectimage = ["color=(100", "200", "120", "55)"]
colswidth = [30, 105, 30, 30]
rowsheight = [25, 32, 32, 32, 32, 32, 32, 32]
normallineheight = 32
fontlist1 = "INTERFACE_MENU"
fontlist2 = "bold_numbers"

[TABLE_SKILL_1]
command = ["click", "select:TABLE_SKILL_1", "rclick", "select:TABLE_SKILL_1", "event:ShowInfoWindow", "deactivate", "event:exitCancel", "upstep", "downstep"]
position = [518, 58, 721, 311]
vlinewidth = 0
hlineheight = 2
rowquantity = 8
colquantity = 5
fontcellvalignment = "center"
selectimage = ["color=(100", "200", "120", "55)"]
colswidth = [32, 83, 27, 27, 30]
rowsheight = [25, 32, 32, 32, 32, 32, 32, 32]
normallineheight = 32
fontlist1 = "bold_numbers"

[TABLE_SKILL_2]
command = ["click", "select:TABLE_SKILL_2", "rclick", "select:TABLE_SKILL_2", "event:ShowInfoWindow", "deactivate", "event:exitCancel", "upstep", "downstep"]
position = [518, 317, 721, 570]
vlinewidth = 0
hlineheight = 2
rowquantity = 8
colquantity = 5
fontcellvalignment = "center"
selectimage = ["color=(100", "200", "120", "55)"]
colswidth = [32, 83, 27, 27, 30]
rowsheight = [25, 32, 32, 32, 32, 32, 32, 32]
normallineheight = 32
fontlist1 = "bold_numbers"

[TABLE_PERKS]
command = ["click", "select:TABLE_PERKS", "rclick", "select:TABLE_PERKS", "event:ShowInfoWindow", "dblclick", "select:TABLE_PERKS", "event:ChoosePerk", "deactivate", "event:exitCancel", "upstep", "downstep"]
position = [90, 349, 286, 570]
scroller = "SCROLL_PERKS"
vlinewidth = 0
hlineheight = 2
rowquantity = 7
colquantity = 2
fontcellvalignment = "center"
selectimage = ["color=(100", "200", "120", "55)"]
colswidth = [32, 160]
rowsheight = [25, 32, 32, 32, 32, 32, 32]
normallineheight = 32

[SCROLL_PERKS]
command = ["click", "select:TABLE_PERKS", "deactivate", "event:exitCancel", "downstep", "upstep"]
position = [275, 352, 283, 567]
basetexture = "interfaces\\icons.tga"
rollertexture = "interfaces\\icons.tga"
scrolltexpos = [0.0, 0.75, 0.045, 1.0]
rolltexpos = [0.0625, 0.875, 0.1075, 0.96]
begendtexsize = 0.0835
begendbasesize = 18
rollerheight = 18
ownedcontrol = "TABLE_PERKS"

[TABLE_OTHER]
command = ["click", "select:TABLE_OTHER", "rclick", "select:TABLE_OTHER", "event:ShowInfoWindow", "deactivate", "event:exitCancel", "upstep", "downstep"]
position = [299, 345, 510, 570]
vlinewidth = 0
hlineheight = 2
rowquantity = 9
colquantity = 4
fontcellvalignment = "center"
selectimage = ["color=(100", "200", "120", "55)"]
colswidth = [35, 80, 87, 5]
rowsheight = [1, 27, 27, 28, 28, 27, 28, 28, 27]
normallineheight = 31

[HERO_NAME]
position = [302, 64, 507, 90]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[STR_1]
position = [85, 62, 290, 88]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[STR_2]
position = [517, 62, 722, 88]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[STR_3]
position = [517, 322, 722, 348]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[STR_4]
position = [89, 354, 294, 380]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[FREE_SPECIAL]
position = [260, 61, 287, 87]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[FREE_SKILL]
position = [680, 61, 718, 87]
linespace = 19
font = ["INTERFACE_TITLE", "0.9"]

[LOYALITY]
position = [300, 320, 510, 335]

[BAR_HEALTH]
position = [336, 423, 412, 426]

[REPUTATION_STR]
command = ["deactivate", "event:exitCancel", "click", "rclick", "select:REPUTATION_STR", "event:ShowInfoWindow"]
position = [300, 300, 510, 320]
linespace = 13
color = [255, 255, 255, 255]
font = "INTERFACE_ULTRASMALL"
bshowglowcursor = 0

[LOYALITY_STR]
command = ["deactivate", "event:exitCancel", "click", "rclick", "select:LOYALITY_STR", "event:ShowInfoWindow"]
position = [300, 320, 510, 335]
linespace = 13
color = [255, 255, 255, 255]
font = "INTERFACE_ULTRASMALL"
bshowglowcursor = 0

[TABBTN_1]
command = ["deactivate", "event:exitCancel", "click", "event:eTabControlPress", "rclick", "select:TABBTN_1", "event:ShowInfoWindow"]
position = [90, 325, 176, 350]
groupname = "TABS"
picname = "TabDeSelected"
bshowglowcursor = 0

[TABSTR_1]
position = [90, 332, 176, 357]
fontscale = 0.8
linespace = 12
valignment = 1
string = "Personal_abilities"

[TABBTN_2]
command = ["deactivate", "event:exitCancel", "click", "event:eTabControlPress", "rclick", "select:TABBTN_2", "event:ShowInfoWindow"]
position = [176, 325, 262, 350]
groupname = "TABS"
picname = "TabSelected"
bshowglowcursor = 0

[TABSTR_2]
position = [170, 332, 269, 357]
fontscale = 0.8
linespace = 12
valignment = 1
string = "Ship_abilities"

[SUBSTRATE]
offset = [674, -397]
groupname = "SKILLS"
picture = ["skillborder", "col:{255", "128", "128", "128}", "pos:{302", "60", "506", "85}"]

[CHARACTER_BIG_PICTURE_BORDER]
offset = [-70, -20]

[MSG_WINDOW]
show = 0
nodelist = ["MSG_FADER", "MSG_OK", "MSG_WINDOW_FRAME", "MSG_WINDOW_CAPTION", "MSG_WINDOW_TEXT", "MSG_EXIT_BTN"]

[MSG_WINDOW_CAPTION]
command = "click"
babsoluterectangle = 5
position = [247, 192, 555, 224]
font = ["interface_button", "1.0"]
linespace = 10
alignment = "center"
color = [255, 255, 255, 255]
backoffset = [1, 2, 0, -2]

[MSG_WINDOW_TEXT]
command = "click"
position = [193, 228, 610, 340]
fontscale = 1.0
linespace = 20
alignment = "center"
color = [255, 255, 255, 255]

[MSG_FADER]
babsoluterectangle = 5
position = [0, 0, 800, 600]
leftcolor = [150, 0, 0, 0]
topcolor = [150, 0, 0, 0]
rightcolor = [150, 0, 0, 0]
bottomcolor = [150, 0, 0, 0]
bordercolor = [0, 0, 0, 0]

[MSG_OK]
bbreakcommand = 1
command = ["activate", "event:ExitMsgMenu", "click", "event:ExitMsgMenu", "deactivate", "event:ExitMsgMenu"]
position = [320, 344, 480, 374]
string = "Ok"
glowoffset = [0, 0]

[MSG_WINDOW_FRAME]
position = [179, 186, 624, 382]
captionheight = 28
captionimage = ["piclist=SKILLS", "picname=SKILLBORDER", "color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4

[MSG_EXIT_BTN]
position = [596, 191, 618, 213]
group = "ICONS_SPEC"
picture = ["exit", "button"]
command = ["click", "event:ExitMsgMenu"]
shadowcolor = [0, 0, 0, 0]
