[MAIN]
item = [["PICTURE", "MAIN_BACK"], ["TITLE", "TITLE"], ["100", "pc", "BUTTON", "EXIT_BTN"], ["120", "PICTURE", "TABBTN_1"], ["125", "FORMATEDTEXT", "TABSTR_1"], ["120", "PICTURE", "TABBTN_2"], ["125", "FORMATEDTEXT", "TABSTR_2"], ["120", "PICTURE", "TABBTN_3"], ["125", "FORMATEDTEXT", "TABSTR_3"], ["120", "PICTURE", "TABBTN_4"], ["125", "FORMATEDTEXT", "TABSTR_4"], ["200", "TABLE", "TABLE_ITEMS"], ["201", "SCROLLER", "SCROLL_ITEMS"], ["400", "TEXTBUTTON2", "EQUIP_BUTTON"], ["200", "BUTTON", "I_CHARACTER_2"], ["200", "BUTTON", "I_SHIP_2"], ["200", "BUTTON", "I_QUESTBOOK_2"], ["200", "BUTTON", "I_NATIONS_2"], ["200", "BUTTON", "I_TRADEBOOK_2"], ["100", "pc", "BUTTON", "I_CHARACTER"], ["100", "pc", "BUTTON", "I_SHIP"], ["100", "pc", "BUTTON", "I_QUESTBOOK"], ["100", "pc", "BUTTON", "I_NATIONS"], ["100", "pc", "BUTTON", "I_TRADEBOOK"], ["STRINGCOLLECTION", "STR_BUTTONS"], ["FRAME", "CHARACTERS_SCROLL_FRAME"], ["400", "RECTANGLE", "CHARACTERS_BACK"], ["400", "RECTANGLE", "CHARACTERS_BACK_HI"], ["400", "VIMAGESCROLL", "CHARACTERS_SCROLL"], ["400", "BUTTON", "UP_BUTTON"], ["400", "BUTTON", "DOWN_BUTTON"], ["555", "FORMATEDTEXT", "SETUP_FRAME_CAPTION"], ["FRAME", "SETUP_FRAME"], ["403", "PICTURE", "ITEM_1"], ["403", "PICTURE", "ITEM_2"], ["403", "PICTURE", "ITEM_3"], ["403", "PICTURE", "ITEM_4"], ["403", "PICTURE", "ITEM_5"], ["403", "PICTURE", "ITEM_6"], ["403", "PICTURE", "ITEM_7"], ["403", "PICTURE", "SLOT_ITEM_1"], ["403", "PICTURE", "SLOT_ITEM_2"], ["403", "PICTURE", "SLOT_ITEM_3"], ["405", "PICTURE", "SLOT_PIC_1"], ["405", "PICTURE", "SLOT_PIC_2"], ["405", "PICTURE", "SLOT_PIC_3"], ["555", "FORMATEDTEXT", "SLOT1_TEXT"], ["555", "FORMATEDTEXT", "SLOT2_TEXT"], ["555", "FORMATEDTEXT", "SLOT3_TEXT"], ["402", "PICTURE", "SETUP_BIG_PICTURE"], ["FRAME", "INFO_FRAME"], ["403", "PICTURE", "INFO_PIC"], ["555", "FORMATEDTEXT", "INFO_TEXT"], ["403", "PICTURE", "Weight_PIC"], ["555", "FORMATEDTEXT", "Weight_TEXT"], ["403", "PICTURE", "Money_PIC"], ["555", "FORMATEDTEXT", "Money_TEXT"], ["WINDOW", "MAIN_WINDOW"], ["606", "pc", "BUTTON", "MAP_EXIT_BTN"], ["600", "RECTANGLE", "MAP_FADER"], ["600", "FRAME", "MAP_FRAME"], ["600", "FORMATEDTEXT", "MAP_CAPTION"], ["600", "PICTURE", "MAP_PICTURE"], ["600", "FORMATEDTEXT", "MAP_TEXT"], ["WINDOW", "MAP_WINDOW"]]
start = "TABLE_ITEMS"

[MAIN_WINDOW]
show = 1
nodelist = [["EXIT_BTN", "I_CHARACTER_2", "I_QUESTBOOK_2", "I_NATIONS_2", "I_TRADEBOOK_2", "I_SHIP_2", "I_CHARACTER", "I_QUESTBOOK", "I_NATIONS", "I_TRADEBOOK", "I_SHIP"], ["TABBTN_1", "TABSTR_1", "TABBTN_2", "TABSTR_2", "TABBTN_3", "TABSTR_3", "TABBTN_4", "TABSTR_4"], ["CHARACTERS_SCROLL_FRAME", "UP_BUTTON", "DOWN_BUTTON", "EQUIP_BUTTON", "SCROLL_ITEMS", "TABLE_ITEMS"]]

[MAIN_BACK]
babsoluterectangle = 5
position = [0, 0, 800, 600]
texturename = "interfaces\\card_desk.tga"

[EXIT_BTN]
position = [774, 45, 796, 67]
group = "ICONS_SPEC"
picture = "exit button"
command = ["click", "event:exitCancel"]
shadowcolor = [0, 0, 0, 0]

[STR_BUTTONS]
string = [["buttonCharacter", "font:INTERFACE_TITLE", "pos:{70", "15}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:0.7", "state:{S}"], ["buttonShip", "font:INTERFACE_TITLE", "pos:{230", "15}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:0.7", "state:{S}"], ["buttonQuestBook", "font:INTERFACE_TITLE", "pos:{390", "15}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:0.7", "state:{S}"], ["buttonNation", "font:INTERFACE_TITLE", "pos:{550", "15}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:0.7", "state:{S}"], ["buttonTradeBook", "font:INTERFACE_TITLE", "pos:{710", "15}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:0.7", "state:{S}"]]

[I_CHARACTER]
bbreakcommand = 1
command = ["click", ["deactivate", "event:exitCancel"]]
group = "ICONS_SPEC"
picture = "pers button"
position = [0, 0, 50, 50]
shadowcolor = [0, 0, 0, 0]

[I_SHIP]
bbreakcommand = 1
command = ["click", ["deactivate", "event:exitCancel"]]
group = "ICONS_SPEC"
picture = "ship button"
position = [160, 0, 210, 50]
shadowcolor = [0, 0, 0, 0]

[I_QUESTBOOK]
bbreakcommand = 1
command = ["click", ["deactivate", "event:exitCancel"]]
group = "ICONS_SPEC"
picture = "questbook button"
position = [320, 0, 370, 50]
shadowcolor = [0, 0, 0, 0]

[I_NATIONS]
bbreakcommand = 1
command = ["click", ["deactivate", "event:exitCancel"]]
group = "ICONS_SPEC"
picture = "nations button"
position = [480, 0, 530, 50]
shadowcolor = [0, 0, 0, 0]

[I_TRADEBOOK]
bbreakcommand = 1
command = ["click", ["deactivate", "event:exitCancel"]]
group = "ICONS_SPEC"
picture = "trade button"
position = [640, 0, 690, 50]
shadowcolor = [0, 0, 0, 0]

[I_CHARACTER_2]
bbreakcommand = 1
command = "click"
position = [50, 0, 160, 39]

[I_SHIP_2]
bbreakcommand = 1
command = "click"
position = [210, 0, 320, 39]

[I_QUESTBOOK_2]
bbreakcommand = 1
command = "click"
position = [370, 0, 480, 39]

[I_NATIONS_2]
bbreakcommand = 1
command = "click"
position = [530, 0, 640, 39]

[I_TRADEBOOK_2]
bbreakcommand = 1
command = "click"
position = [690, 0, 800, 39]

[TITLE]
position = [0, 40, 800, 72]

[UP_BUTTON]
command = ["click", "select:CHARACTERS_SCROLL", "com:upstep:CHARACTERS_SCROLL", "com:activate:UP_BUTTON"]
position = [12, 90, 76, 100]
group = "MAIN_ICONS"
picture = "upbutton"
shadowoffset = [0, 0]

[DOWN_BUTTON]
command = ["click", "select:CHARACTERS_SCROLL", "com:downstep:CHARACTERS_SCROLL", "com:activate:DOWN_BUTTON"]
group = "MAIN_ICONS"
picture = "downbutton"
position = [12, 558, 76, 568]
shadowoffset = [0, 0]

[CHARACTERS_SCROLL_FRAME]
position = [5, 78, 151, 590]
backimage = ["piclist=PAPIRUS", " picname=papirus_characters_list", " color=(255", "128", "128", "128)"]

[CHARACTERS_BACK]
position = [13, 299, 144, 360]
leftcolor = [120, 41, 17, 0]
topcolor = [120, 41, 17, 0]
rightcolor = [120, 41, 17, 0]
bottomcolor = [120, 41, 17, 0]
bordercolor = [255, 106, 76, 57]

[CHARACTERS_BACK_HI]
position = [13, 299, 144, 360]
leftcolor = [150, 200, 200, 200]
topcolor = [150, 200, 200, 200]
rightcolor = [150, 200, 200, 2000]
bottomcolor = [150, 200, 200, 200]
bordercolor = [255, 0, 0, 0]

[CHARACTERS_SCROLL]
busewheel = 1
command = [["rclick", "select:CHARACTERS_SCROLL", "event:ShowInfoWindow"], ["click", "select:CHARACTERS_SCROLL"], ",upstep", "downstep", ["deactivate", "event:exitCancel"], ["activate", "select:CHARACTERS_SCROLL", "event:OfficerChange"]]
imagesize = [64, 64]
wdelta = 1
position = [12, 101, 76, 556]
glowoffset = [0, 0]
centeryoffset = 228
stringsquantity = 5
dwxoffset1 = 36
dwyoffset1 = -30
scale1 = 0.8
align1 = "left"
font1 = "interface_normal"
dwforecolor1 = [255, 255, 255, 255]
dwbackcolor1 = [0, 0, 0, 0]
dwxoffset2 = 36
dwyoffset2 = 0
scale2 = 0.8
align2 = "left"
font2 = "interface_normal"
dwforecolor2 = [255, 255, 255, 255]
dwbackcolor2 = [0, 0, 0, 0]
dwxoffset3 = 36
dwyoffset3 = 16
scale3 = 0.8
align3 = "left"
font3 = "interface_normal"
dwforecolor3 = [255, 255, 255, 255]
dwbackcolor3 = [0, 0, 0, 0]
dwxoffset4 = 36
dwyoffset4 = -15
scale4 = 0.8
align4 = "left"
font4 = "interface_normal"
dwforecolor4 = [255, 255, 255, 255]
dwbackcolor4 = [0, 0, 0, 0]
dwxoffset5 = 28
dwyoffset5 = 6
scale5 = 0.7
align5 = "right"
font5 = "Bold_numbers"
dwforecolor5 = [255, 255, 255, 255]
dwbackcolor5 = [0, 0, 0, 0]
lefttextlimit = 0
righttextlimit = 100

[SETUP_FRAME]
captionheight = 24
captionimage = ["piclist=SKILLS", " picname=SKILLBORDER", " color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4
position = [507, 78, 792, 458]

[SETUP_FRAME_CAPTION]
command = "click"
position = [495, 82, 803, 108]
font = "interface_button"
fontscale = 1.0
linespace = 10

[SETUP_BIG_PICTURE]
position = [511, 105, 788, 455]
texturename = "interfaces\\CharacterEquipment_SLIB.tga"
bshowglowcursor = 0

[INFO_FRAME]
position = [159, 463, 792, 590]
backimage = ["piclist=PAPIRUS", " picname=papirus_info", " color=(255", "128", "128", "128)"]

[TABBTN_1]
command = [["deactivate", "event:exitCancel"], ["click", "event:eTabControlPress"], ["rclick", "select:TABBTN_1", "event:ShowInfoWindow"]]
position = [159, 78, 245, 103]
groupname = "TABS"
picname = "TabDeSelected"
bshowglowcursor = 0

[TABSTR_1]
position = [159, 78, 245, 103]
fontscale = 0.8
linespace = 12
valignment = 1
string = "All"

[TABBTN_2]
command = [["deactivate", "event:exitCancel"], ["click", "event:eTabControlPress"], ["rclick", "select:TABBTN_2", "event:ShowInfoWindow"]]
position = [245, 78, 331, 103]
groupname = "TABS"
picname = "TabSelected"
bshowglowcursor = 0

[TABSTR_2]
position = [239, 78, 338, 103]
fontscale = 0.8
linespace = 12
valignment = 1
string = "Item_WEAPON"

[TABBTN_3]
command = [["deactivate", "event:exitCancel"], ["click", "event:eTabControlPress"], ["rclick", "select:TABBTN_3", "event:ShowInfoWindow"]]
position = [330, 78, 416, 103]
groupname = "TABS"
picname = "TabSelected"
bshowglowcursor = 0

[TABSTR_3]
position = [330, 78, 416, 103]
fontscale = 0.8
linespace = 12
valignment = 1
string = "Item_VARIETY"

[TABBTN_4]
command = [["deactivate", "event:exitCancel"], ["click", "event:eTabControlPress"], ["rclick", "select:TABBTN_4", "event:ShowInfoWindow"]]
position = [416, 78, 502, 103]
groupname = "TABS"
picname = "TabSelected"
bshowglowcursor = 0

[TABSTR_4]
position = [416, 78, 502, 103]
fontscale = 0.8
linespace = 12
valignment = 1
string = "Item_AMULET"

[TABLE_ITEMS]
command = [["click", "select:TABLE_ITEMS"], ["rclick", "select:TABLE_ITEMS", "event:ShowInfoWindow"], ["dblclick", "select:TABLE_ITEMS", "event:ChooseItem"], ["deactivate", "event:exitCancel"], ",upstep", "downstep"]
position = [159, 103, 415, 324]
scroller = "SCROLL_ITEMS"
vlinewidth = 2
hlineheight = 2
rowquantity = 11
colquantity = 4
fontcellvalignment = "center"
selectimage = ["color=(100", "200", "120", "55)"]
colswidth = [198, 45, 45, 45]
rowsheight = [31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
normallineheight = 32

[SCROLL_ITEMS]
command = [["click", " select:TABLE_ITEMS"], ["deactivate", "event:exitCancel"], ",downstep", "upstep"]
position = [495, 103, 503, 458]
basetexture = "interfaces\\icons.tga"
rollertexture = "interfaces\\icons.tga"
scrolltexpos = [0.0, 0.75, 0.045, 1.0]
rolltexpos = [0.0625, 0.875, 0.1075, 0.96]
begendtexsize = 0.0835
begendbasesize = 18
rollerheight = 18
ownedcontrol = "TABLE_ITEMS"

[ITEM_1]
position = [700, 206, 768, 274]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[ITEM_2]
position = [532, 206, 600, 274]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[ITEM_3]
position = [532, 286, 600, 354]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[ITEM_4]
position = [616, 206, 684, 274]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[ITEM_5]
position = [700, 126, 768, 194]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[ITEM_6]
position = [532, 126, 600, 194]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[ITEM_7]
position = [700, 286, 768, 354]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[SLOT_ITEM_1]
position = [532, 366, 600, 434]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[SLOT_ITEM_2]
position = [616, 366, 684, 434]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[SLOT_ITEM_3]
position = [700, 366, 768, 434]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[SLOT_PIC_1]
position = [532, 366, 600, 434]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[SLOT_PIC_2]
position = [616, 366, 684, 434]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[SLOT_PIC_3]
position = [700, 366, 768, 434]
texturename = "interfaces\\empty_item.tga"
bshowglowcursor = 0

[SLOT1_TEXT]
position = [537, 371, 567, 391]
fontscale = 0.8
linespace = 16
alignment = "center"

[SLOT2_TEXT]
position = [621, 371, 651, 391]
fontscale = 0.8
linespace = 16
alignment = "center"

[SLOT3_TEXT]
position = [705, 371, 735, 391]
fontscale = 0.8
linespace = 16
alignment = "center"

[INFO_PIC]
position = [333, 477, 433, 577]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[INFO_TEXT]
position = [416, 470, 804, 583]
fontscale = 0.9
linespace = 16
alignment = "center"

[Weight_PIC]
position = [168, 549, 198, 579]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[Weight_TEXT]
position = [204, 557, 325, 576]
fontscale = 0.95
linespace = 16
alignment = "left"

[Money_PIC]
position = [168, 515, 198, 545]
texturename = "interfaces\\empty_spyglass.tga"
bshowglowcursor = 0

[Money_TEXT]
position = [187, 523, 331, 542]
fontscale = 1.0
linespace = 16
alignment = "center"
color = [255, 255, 228, 80]

[EQUIP_BUTTON]
command = ["activate", "click", ["deactivate", "event:exitCancel"]]
position = [170, 478, 323, 506]
string = "Equip that"
fontscale = 0.9
glowoffset = [0, 0]

[MAP_FRAME]
position = [40, 15, 760, 589]
captionheight = 28
captionimage = ["piclist=SKILLS", " picname=SKILLBORDER", " color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4

[MAP_FADER]
babsoluterectangle = 5
position = [0, 0, 800, 600]
leftcolor = [150, 0, 0, 0]
topcolor = [150, 0, 0, 0]
rightcolor = [150, 0, 0, 0]
bottomcolor = [150, 0, 0, 0]
bordercolor = [0, 0, 0, 0]

[MAP_CAPTION]
babsoluterectangle = 5
position = [245, 20, 578, 50]
font = "interface_button"
fontscale = 1.0
linespace = 10
alignment = "center"
backoffset = [1, 2, 0, -2]
string = "titleMapRead"

[MAP_EXIT_BTN]
position = [731, 20, 753, 42]
group = "ICONS_SPEC"
picture = "exit button"
command = ["click", "event:ExitMapWindow"]
shadowcolor = [0, 0, 0, 0]
bshowglowcursor = 0
glowoffset = [0, 0]

[MAP_TEXT]
command = ["click", ["deactivate", "event:ExitMapWindow"]]
position = [190, 99, 621, 504]
fontscale = 1.5
linespace = 30
alignment = "center"
font = "interface_button"
bshowglowcursor = 0

[MAP_PICTURE]
position = [50, 50, 750, 580]
texturename = "interfaces\\CharacterEquipment_SLIB.tga"
bshowglowcursor = 0

[MAP_WINDOW]
show = 0
nodelist = ["MAP_FRAME", "MAP_EXIT_BTN", "MAP_FADER", "MAP_CAPTION", "MAP_TEXT", "MAP_PICTURE"]
