[MAIN]
item = ["VIDEO", "VIDEOBASE", "PICTURE", "MAIN_BACK", "PICTURE", "BOUNDARIES", "TITLE", "TITLE", "SCROLLEDPICTURE", "MAP", "IMAGECOLLECTION", "BORDERS", "100", "pc", "BUTTON", "EXIT_BTN", "WINDOW", "MAIN_WINDOW", "400", "RECTANGLE", "INFO_FADER", "401", "IMAGECOLLECTION", "INFO_BACK", "401", "IMAGECOLLECTION", "INFO_BORDERS", "401", "FORMATEDTEXT", "INFO_CAPTION", "401", "PICTURE", "INFO_NATION_PICTURE", "401", "FORMATEDTEXT", "COLONY_INFO_TEXT", "401", "FORMATEDTEXT", "COLONY_INFO_TEXT2", "401", "FORMATEDTEXT", "COLONY_INFO_SIEGE", "401", "FORMATEDTEXT", "COLONY_INFO_LABEL", "401", "FORMATEDTEXT", "COLONY_TIME_INFO", "401", "FORMATEDTEXT", "COLONY_TRAVEL_INFO", "401", "FORMATEDTEXT", "IMPORT_CAPTION", "401", "FORMATEDTEXT", "EXPORT_CAPTION", "401", "FORMATEDTEXT", "CONTRABAND_CAPTION", "401", "FORMATEDTEXT", "AGGRESSIVE_CAPTION", "401", "IMAGECOLLECTION", "GOODS_PICTURES", "401", "FORMATEDTEXT", "TRADEASSISTANT_CAPTION", "401", "FORMATEDTEXT", "TRADEASSISTANT_TO", "401", "FORMATEDTEXT", "TRADEASSISTANT_FROM", "401", "FORMATEDTEXT", "TRADEASSISTANT_PRICES1", "401", "FORMATEDTEXT", "TRADEASSISTANT_PRICES2", "401", "FORMATEDTEXT", "TRADEASSISTANT_SPECIAL", "WINDOW", "INFO_WINDOW"]

[MAIN_WINDOW]
show = 1
nodelist = ["MAIN_BACK", "BOUNDARIES", "TITLE", "BACK", "MAP", "MAPS_LIST", "BORDERS", "EXIT_BTN"]

[INFO_WINDOW]
show = 0
nodelist = ["INFO_BORDERS", "INFO_FADER", "INFO_BACK", "INFO_CAPTION", "INFO_NATION_PICTURE", "COLONY_INFO_TEXT", "COLONY_INFO_TEXT2", "COLONY_INFO_LABEL", "COLONY_INFO_SIEGE", "COLONY_INFO", "COLONY_TIME_INFO", "COLONY_TRAVEL_INFO", "IMPORT_CAPTION", "EXPORT_CAPTION", "CONTRABAND_CAPTION", "AGGRESSIVE_CAPTION", "GOODS_PICTURES", "TRADEASSISTANT_PRICES1", "TRADEASSISTANT_PRICES2", "TRADEASSISTANT_CAPTION", "TRADEASSISTANT_TO", "TRADEASSISTANT_FROM", "TRADEASSISTANT_SPECIAL"]

[INFO_FADER]
babsoluterectangle = 5
position = [0, 33, 800, 600]
leftcolor = [200, 0, 0, 0]
topcolor = [200, 0, 0, 0]
rightcolor = [200, 0, 0, 0]
bottomcolor = [200, 0, 0, 0]
bordercolor = [0, 0, 0, 0]

[MAIN_BACK]
position = [0, 35, 800, 595]
texturename = "interfaces\\maps\\map_good.tga"

[BOUNDARIES]
position = [0, 35, 800, 595]

[EXIT_BTN]
position = [770, 5, 795, 30]
group = "ICONS_SPEC"
picture = ["exit", "button"]
command = ["click", "event:exitCancel"]
shadowcolor = [0, 0, 0, 0]

[MAP]
command = ["click", "rclick", "event:SelectRColony"]
position = [19, 55, 789, 585]
basesize = [2048, 2048]
scale1 = [1, 1]
startscale = 1

[BORDERS]
groupname = "MAIN_ICONS"
picture = ["editsection:map", "BORDER_UPLEFT", "col:{255", "128", "128", "128}", "pos:{0", "33", "9", "42}", "BORDER_CENTER", "col:{255", "128", "128", "128}", "pos:{9", "33", "791", "38}", "BORDER_UPRIGHT", "col:{255", "128", "128", "128}", "pos:{791", "33", "800", "42}", "BORDER_CENTER", "col:{255", "128", "128", "128}", "pos:{0", "595", "790", "600}", "BORDER_LEFT", "col:{255", "128", "128", "128}", "pos:{0", "42", "5", "591}", "BORDER_LEFT", "col:{255", "128", "128", "128}", "pos:{795", "42", "800", "591}", "BORDER_DOWNLEFT", "col:{255", "128", "128", "128}", "pos:{0", "591", "9", "600}", "BORDER_DOWNRIGHT", "col:{255", "128", "128", "128}", "pos:{791", "591", "800", "600}", "editsection:end"]

[INFO_CAPTION]
position = [304, 124, 498, 153]
linespace = 16
alignment = "center"
font = "interface_button"

[INFO_BORDERS]
groupname = "MAIN_ICONS"
picture = ["editsection:UP", "SKILLBORDER", "col:{255", "128", "128", "128}", "pos:{204", "120", "593", "145}", "BORDER_CENTER", "col:{255", "128", "128", "128}", "pos:{209", "118", "589", "123}", "BORDER_CENTER", "col:{255", "128", "128", "128}", "pos:{205", "144", "593", "149}", "editsection:left", "BORDER_UPLEFT", "col:{255", "128", "128", "128}", "pos:{201", "118", "210", "127}", "BORDER_LEFT", "col:{255", "128", "128", "128}", "pos:{201", "127", "206", "542}", "BORDER_DOWNLEFT", "col:{255", "128", "128", "128}", "pos:{201", "533", "210", "542}", "editsection:right", "BORDER_UPRIGHT", "col:{255", "128", "128", "128}", "pos:{585", "118", "594", "127}", "BORDER_LEFT", "col:{255", "128", "128", "128}", "pos:{589", "127", "594", "542}", "BORDER_DOWNRIGHT", "col:{255", "128", "128", "128}", "pos:{585", "533", "594", "542}", "editsection:down", "BORDER_CENTER", "col:{255", "128", "128", "128}", "pos:{210", "537", "585", "542}"]

[INFO_BACK]
offset = [-432, 69]
groupname = "PAPIRUS"
picture = ["editsection:colonylist", "papirus_papermap_info", "col:{255", "128", "128", "128}", "pos:{206", "119", "593", "541}"]

[INFO_NATION_PICTURE]
position = [220, 155, 285, 220]

[COLONY_TRAVEL_INFO]
position = [276, 162, 585, 182]
linespace = 16
alignment = "center"

[COLONY_TIME_INFO]
position = [276, 182, 585, 220]
linespace = 16
alignment = "center"

[COLONY_INFO_LABEL]
position = [220, 225, 365, 243]
linespace = 18
alignment = "left"

[COLONY_INFO_TEXT]
position = [220, 250, 365, 380]
fontscale = 0.8
linespace = 20
alignment = "left"

[COLONY_INFO_TEXT2]
position = [375, 250, 400, 380]
fontscale = 0.8
linespace = 20
alignment = "left"

[COLONY_INFO_SIEGE]
position = [220, 380, 500, 460]
fontscale = 0.8
linespace = 20
alignment = "left"
color = [255, 255, 168, 168]

[EXPORT_CAPTION]
babsoluterectangle = 5
position = [400, 225, 600, 250]
linespace = 16
font = "interface_button"
color = [255, 196, 255, 196]
alignment = "center"

[IMPORT_CAPTION]
babsoluterectangle = 5
position = [400, 310, 600, 335]
linespace = 16
font = "interface_button"
color = [255, 196, 196, 255]
alignment = "center"

[CONTRABAND_CAPTION]
babsoluterectangle = 5
position = [400, 395, 600, 420]
linespace = 16
font = "interface_button"
color = [255, 220, 20, 60]
alignment = "center"

[AGGRESSIVE_CAPTION]
babsoluterectangle = 5
position = [400, 450, 600, 475]
linespace = 16
font = "interface_button"
color = [255, 255, 174, 100]
alignment = "center"

[GOODS_PICTURES]
groupname = "GOODS"

[TRADEASSISTANT_CAPTION]
babsoluterectangle = 5
position = [265, 364, 335, 384]
linespace = 16
font = "interface_button"
color = [255, 255, 127, 80]
alignment = "center"

[TRADEASSISTANT_TO]
babsoluterectangle = 5
position = [235, 385, 290, 401]
linespace = 16
font = ["interface_button", "0.75"]
alignment = "center"

[TRADEASSISTANT_FROM]
babsoluterectangle = 5
position = [315, 385, 370, 401]
linespace = 16
font = ["interface_button", "0.75"]
alignment = "center"

[TRADEASSISTANT_PRICES1]
position = [265, 401, 295, 600]
fontscale = 1
linespace = 28
alignment = "left"

[TRADEASSISTANT_PRICES2]
position = [345, 401, 375, 600]
fontscale = 1
linespace = 28
alignment = "left"

[TRADEASSISTANT_SPECIAL]
babsoluterectangle = 5
position = [235, 385, 370, 401]
linespace = 16
fontscale = 0.8
font = "interface_button"
alignment = "center"
