[MAIN]
item = [["WINDOW", "MAIN_WINDOW"], ["PICTURE", "MAIN_BACK"], ["TITLE", "TITLE"], ["404", "pc", "BUTTON", "EXIT_BTN"], ["420", "IMAGECOLLECTION", "CHARACTER_BIG_PICTURE_BORDER"], ["400", "IMAGECOLLECTION", "SUBSTRATE"], ["PICTURE", "FACEPICT"], ["420", "FORMATEDTEXT", "HERO_NAME"], ["504", "BUTTON", "LEFTCHANGE_CHARACTER"], ["504", "BUTTON", "RIGHTCHANGE_CHARACTER"], ["100", "PICTURE", "NATIONS_PICTURE"], ["FRAME", "INFO_FRAME"], ["555", "FORMATEDTEXT", "INFO_TEXT"], ["555", "FORMATEDTEXT", "INFO_FRAME_CAPTION"], ["555", "FORMATEDTEXT", "STATE_FRAME_CAPTION"], ["FRAME", "STATE_FRAME"], ["420", "FORMATEDTEXT", "COMPLEX_TYPE"], ["512", "CHECKBUTTON", "CHECK_ARCADESAIL"], ["555", "FORMATEDTEXT", "CHECK_ARCADESAIL_NAME"], ["555", "FORMATEDTEXT", "CHECK_OTHER_NAME"], ["512", "CHECKBUTTON", "CHECK_PISTOL"], ["512", "CHECKBUTTON", "CHECK_HARDCORE"], ["512", "CHECKBUTTON", "CHECK_PARTITION"], ["512", "CHECKBUTTON", "CHECK_SEABATTLESAVE"], ["512", "CHECKBUTTON", "CHECK_RAINS"], ["600", "BUTTON", "LEFTCHANGE_COMPLEX"], ["600", "BUTTON", "RIGHTCHANGE_COMPLEX"], ["555", "FORMATEDTEXT", "PROFILE_STR"], ["404", "TEXTBUTTON2", "OK_BUTTON"], ["404", "TEXTBUTTON2", "CANCEL_BUTTON"], ["400", "PCEDITBOX", "PROFILE_NAME"], ["555", "FORMATEDTEXT", "SETUP_FRAME_CAPTION"], ["FRAME", "SETUP_FRAME"], ["420", "IMAGECOLLECTION", "SETUP_BIG_PICTURE_BORDER"], ["600", "BUTTON", "LEFTCHANGE_SETUP"], ["600", "BUTTON", "RIGHTCHANGE_SETUP"], ["555", "TABLE", "TABLE_SMALLSKILL"], ["555", "FORMATEDTEXT", "SETUP_TEXT"], ["600", "RECTANGLE", "CONFIRM_WINDOW_FADER"], ["600", "IMAGECOLLECTION", "CONFIRM_WINDOW_BACK"], ["600", "IMAGECOLLECTION", "CONFIRM_WINDOW_BORDERS"], ["601", "TEXTBUTTON2", "CONFIRM_WINDOW_MB_YES"], ["601", "TEXTBUTTON2", "CONFIRM_WINDOW_MB_NO"], ["601", "STRINGCOLLECTION", "CONFIRM_WINDOW_STRINGS"], ["WINDOW", " CONFIRM_WINDOW"], ["600", "RECTANGLE", "NOTE_WINDOW_FADER"], ["601", "FRAME", "NOTE_WINDOW_FRAME"], ["602", "FORMATEDTEXT", "NOTE_WINDOW_TEXT"], ["602", "TEXTBUTTON2", "NOTE_WINDOW_OK"], ["WINDOW", "NOTE_WINDOW"]]
start = "OK_BUTTON"

[MAIN_WINDOW]
show = 1
nodelist = [["MAIN_BACK", "TITLE", "EXIT_BTN", "PROFILE_NAME", "CHECK_HARDCORE", "EXP_SLIDE"], ["PROFILE_NAME", "OK_BUTTON", "CANCEL_BUTTON", "LEFTCHANGE_COMPLEX", "RIGHTCHANGE_COMPLEX"], ["CHECK_ENCOUNTERS", "CHECK_ARCADESAIL", "CHECK_PISTOL", "NATIONS_PICTURE"], ["LEFTCHANGE_CHARACTER", "RIGHTCHANGE_CHARACTER", "LEFTCHANGE_SETUP", "RIGHTCHANGE_SETUP"], ["CHECK_PARTITION", "CHECK_SEABATTLESAVE", "CHECK_RAINS", "TABLE_SMALLSKILL"]]

[MAIN_BACK]
babsoluterectangle = 5
position = [0, 0, 800, 600]
texturename = "interfaces\\card_desk.tga"

[TITLE]
position = [0, 22, 800, 54]

[EXIT_BTN]
position = [770, 28, 790, 48]
group = "ICONS_SPEC"
picture = "exit button"
command = ["click", "event:exitCancel"]
shadowcolor = [0, 0, 0, 0]

[LEFTCHANGE_CHARACTER]
bbreakcommand = 1
command = ["activate", "click"]
position = [20, 70, 40, 90]
group = "ICONS"
picture = "small left arrow"

[RIGHTCHANGE_CHARACTER]
bbreakcommand = 1
command = ["activate", "click"]
position = [190, 70, 210, 90]
group = "ICONS"
picture = "small right arrow"

[HERO_NAME]
position = [20, 72, 210, 91]
linespace = 19
font = "INTERFACE_TITLE"
fontscale = 0.9

[FACEPICT]
position = [15, 90, 215, 290]
command = "click"
texturename = "interfaces\\portraits\\256\\face_1.tga"

[NATIONS_PICTURE]
command = ["click", ["rclick", "event:ShowInfo", "select:NATIONS_PICTURE"]]
position = [23, 97, 59, 133]

[SUBSTRATE]
offset = [387, -390]
groupname = "SKILLS"
picture = ["skillborder", "col:{255", "128", "128", "128}", "pos:{15", "67", "215", "94}"]

[INFO_FRAME]
captionheight = 24
captionimage = ["piclist=SKILLS", " picname=SKILLBORDER", " color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4
position = [230, 67, 785, 290]
backimage = ["piclist=PAPIRUS", " picname=papirus_choose_nation_descr", " color=(255", "128", "128", "128)"]

[INFO_FRAME_CAPTION]
command = "click"
position = [234, 70, 780, 91]
font = "INTERFACE_TITLE"
fontscale = 0.9
linespace = 10
string = "titleBiography"

[INFO_TEXT]
command = "click"
position = [234, 101, 780, 281]
fontscale = 0.85
linespace = 15
alignment = "center"
color = [255, 255, 255, 255]

[STATE_FRAME_CAPTION]
command = "click"
position = [19, 308, 212, 330]
font = "INTERFACE_TITLE"
fontscale = 0.9
linespace = 10
string = "m_Complexity"

[STATE_FRAME]
captionheight = 24
captionimage = ["piclist=SKILLS", " picname=SKILLBORDER", " color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4
position = [15, 305, 215, 585]
backimage = ["piclist=PAPIRUS", " picname=papirus_ship_discrad_goods", " color=(255", "128", "128", "128)"]

[LEFTCHANGE_COMPLEX]
bbreakcommand = 1
command = ["activate", "click"]
position = [25, 350, 45, 370]
group = "ICONS"
picture = "small left arrow"

[RIGHTCHANGE_COMPLEX]
bbreakcommand = 1
command = ["activate", "click"]
position = [180, 350, 200, 370]
group = "ICONS"
picture = "small right arrow"

[COMPLEX_TYPE]
command = ["click", ["rclick", "event:ShowInfo", "select:COMPLEX_TYPE"], ["deactivate", "event:exitCancel"]]
position = [15, 350, 215, 370]
fontscale = 1.0
linespace = 20
alignment = "center"
bshowglowcursor = 0

[CHECK_OTHER_NAME]
command = "click"
position = [15, 459, 215, 482]
font = "interface_button"
fontscale = 1.0
linespace = 10
string = "Other"

[CHECK_HARDCORE]
command = ["click", ["rclick", "event:ShowInfo", "select:CHECK_HARDCORE"], ["deactivate", "event:exitCancel"]]
position = [25, 505, 205, 520]
alignment = "left"
fontscale = 0.9
iconsize = [14, 14]
sectioninterval = 4
lineheight = 11
rect_textoffset = [25, 0, 0, 0]
section1 = ["0", "0", "HardcoreGame"]
normalfontcolor = [255, 180, 180, 180]
selectfontcolor = [255, 220, 220, 220]
exclusivechoose = 0
bshowglowcursor = 0

[CHECK_PISTOL]
command = ["click", ["rclick", "event:ShowInfo", "select:CHECK_PISTOL"], ["deactivate", "event:exitCancel"]]
position = [25, 490, 205, 505]
alignment = "left"
fontscale = 0.9
iconsize = [14, 14]
sectioninterval = 4
lineheight = 11
rect_textoffset = [25, 0, 0, 0]
section1 = ["1", "0", "New Fight Mode"]
normalfontcolor = [255, 180, 180, 180]
selectfontcolor = [255, 220, 220, 220]
exclusivechoose = 0
bshowglowcursor = 0

[CHECK_PARTITION]
command = ["click", ["rclick", "event:ShowInfo", "select:CHECK_PARTITION"], ["deactivate", "event:exitCancel"]]
position = [25, 520, 205, 535]
alignment = "left"
fontscale = 0.9
iconsize = [14, 14]
sectioninterval = 4
lineheight = 11
rect_textoffset = [25, 0, 0, 0]
section1 = ["1", "0", "Partition Set"]
normalfontcolor = [255, 180, 180, 180]
selectfontcolor = [255, 220, 220, 220]
exclusivechoose = 0
bshowglowcursor = 0

[CHECK_SEABATTLESAVE]
command = ["click", ["rclick", "event:ShowInfo", "select:CHECK_SEABATTLESAVE"], ["deactivate", "event:exitCancel"]]
position = [25, 535, 205, 550]
alignment = "left"
fontscale = 0.9
iconsize = [14, 14]
sectioninterval = 4
lineheight = 11
rect_textoffset = [25, 0, 0, 0]
section1 = ["1", "0", "Sea Battle Save"]
normalfontcolor = [255, 180, 180, 180]
selectfontcolor = [255, 220, 220, 220]
exclusivechoose = 0
bshowglowcursor = 0

[CHECK_RAINS]
command = ["click", ["rclick", "event:ShowInfo", "select:CHECK_RAINS"], ["deactivate", "event:exitCancel"]]
position = [25, 550, 205, 565]
alignment = "left"
fontscale = 0.9
iconsize = [14, 14]
sectioninterval = 4
lineheight = 11
rect_textoffset = [25, 0, 0, 0]
section1 = ["1", "0", "Rains"]
normalfontcolor = [255, 180, 180, 180]
selectfontcolor = [255, 220, 220, 220]
exclusivechoose = 0
bshowglowcursor = 0

[CHECK_ARCADESAIL]
command = ["click", ["rclick", "event:ShowInfo", "select:CHECK_ARCADESAIL"], ["deactivate", "event:exitCancel"]]
position = [25, 417, 205, 447]
alignment = "left"
fontscale = 0.9
iconsize = [14, 14]
sectioninterval = 4
lineheight = 11
rect_textoffset = [20, 0, 0, 0]
section1 = ["1", "0", "SailType_1"]
section2 = ["0", "0", "SailType_2"]
normalfontcolor = [255, 180, 180, 180]
selectfontcolor = [255, 220, 220, 220]
exclusivechoose = 1
bshowglowcursor = 0

[CHECK_ARCADESAIL_NAME]
command = "click"
position = [15, 386, 215, 409]
font = "interface_button"
fontscale = 1.0
linespace = 10
string = "Sailing Mode"

[LEFTCHANGE_SETUP]
bbreakcommand = 1
command = ["activate", "click"]
position = [360, 308, 380, 328]
group = "ICONS"
picture = "small left arrow"

[RIGHTCHANGE_SETUP]
bbreakcommand = 1
command = ["activate", "click"]
position = [635, 308, 655, 328]
group = "ICONS"
picture = "small right arrow"

[PROFILE_FRAME_CAPTION]
command = "click"
position = [407, 479, 715, 505]
font = "interface_button"
fontscale = 1.0
linespace = 10
string = "Start New Game"

[PROFILE_STR]
command = "click"
position = [251, 547, 405, 567]
font = "interface_button"
fontscale = 1.0
linespace = 10
string = "EnterProfileName"

[SETUP_FRAME_CAPTION]
command = "click"
position = [232, 308, 780, 329]
font = "interface_button"
fontscale = 1.0
linespace = 10
string = "HeroType_1"

[PROFILE_FRAME]
captionheight = 24
captionimage = ["piclist=SKILLS", " picname=SKILLBORDER", " color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4
position = [338, 476, 784, 588]

[SETUP_FRAME]
captionheight = 24
captionimage = ["piclist=SKILLS", " picname=SKILLBORDER", " color=(255", "128", "128", "128)"]
captionoffset = [0, 3, 0, 0]
captiondividerheight = 4
position = [230, 305, 785, 585]

[PROFILE_NAME]
command = [["click", "select:PROFILE_NAME"], ["deactivate", "event:exitCancel"], ["activate", "event:confirmChangeProfileName"]]
position = [405, 545, 567, 572]
strfont = "interface_button"
fontscale = 0.9
argbfontcolor = [255, 255, 255, 255]
stringlength = 30
stringwidth = 208
stringalign = "left"
stringoffset = [4, 4]
middleimage = ["color=(255", "128", "128", "128)", " piclist=MAIN_ICONS", " picname=middle side button"]
excludechars = "* ?.\\/"

[OK_BUTTON]
bbreakcommand = 1
command = [["activate", "event:exitOk"], ["click", "event:exitOk"], ["deactivate", "event:exitCancel"], ["rightstep", "com:click:RIGHTCHANGE_CHARACTER"], ["leftstep", "com:click:LEFTCHANGE_CHARACTER"]]
position = [597, 545, 667, 575]
string = "Ok"
glowoffset = [0, 0]

[CANCEL_BUTTON]
bbreakcommand = 1
command = [["activate", "event:exitCancel"], ["click", "event:exitCancel"], ["deactivate", "event:exitCancel"], ["rightstep", "com:click:RIGHTCHANGE_CHARACTER"], ["leftstep", "com:click:LEFTCHANGE_CHARACTER"]]
position = [677, 545, 774, 575]
string = "Cancel"
glowoffset = [0, 0]

[TABLE_SMALLSKILL]
command = [["click", "select:TABLE_SMALLSKILL"], ["rclick", "select:TABLE_SMALLSKILL", "event:ShowInfo"], ["deactivate", "event:exitCancel"], ",upstep", "downstep"]
position = [358, 338, 656, 423]
vlinewidth = 2
hlineheight = 2
rowquantity = 3
colquantity = 7
fontcellvalignment = "center"
fontcellalignment = "center"
selectimage = ["color=(0", "128", "48", "48)"]
colswidth = [42, 42, 42, 42, 42, 42, 42]
rowsheight = [1, 40, 40]
normallineheight = 28
fontlist1 = "INTERFACE_MENU"
fontlist2 = "INTERFACE_TITLE"

[SETUP_TEXT]
command = ["downstep", "upstep", "speeddown", "speedup", ["deactivate", "event:exitCancel"], ["activate", "select:SETUP_TEXT"], ["click", "select:SETUP_TEXT"]]
bshowglowcursor = 0
position = [230, 426, 785, 531]
fontscale = 0.85
linespace = 15
alignment = "center"
leftoffset = 0
color = [255, 255, 255, 255]

[CONFIRM_WINDOW]
show = 0
nodelist = [["CONFIRM_WINDOW_BORDERS", "CONFIRM_WINDOW_MB_YES", "CONFIRM_WINDOW_MB_NO"], ["CONFIRM_WINDOW_STRINGS", "CONFIRM_WINDOW_FADER", "CONFIRM_WINDOW_BACK"]]

[CONFIRM_WINDOW_BORDERS]

[CONFIRM_WINDOW_BACK]
groupname = "PAPIRUS"
picture = ["editsection:nation", ["papirus_character_remove_officer", "col:{255", "128", "128", "128}", "pos:{190", "190", "610", "360}"]]

[CONFIRM_WINDOW_MB_YES]
command = [["deactivate", "select:CONFIRM_WINDOW_MB_YES"], ["click", "select:CONFIRM_WINDOW_MB_YES"], ["rightstep", "select:CONFIRM_WINDOW_MB_NO"], ",activate"]
position = [238, 300, 402, 332]
glowoffset = 0.0
string = "Yes"

[CONFIRM_WINDOW_MB_NO]
command = [["deactivate", "select:CONFIRM_WINDOW_MB_NO"], ["click", "select:CONFIRM_WINDOW_MB_NO"], ["leftstep", "select:CONFIRM_WINDOW_MB_YES"], ",activate"]
position = [408, 300, 572, 332]
glowoffset = 0.0
string = "No"

[CONFIRM_WINDOW_FADER]
babsoluterectangle = 5
position = [0, 0, 800, 600]
leftcolor = [150, 50, 50, 0]
topcolor = [150, 50, 50, 0]
rightcolor = [150, 50, 50, 0]
bottomcolor = [150, 50, 50, 0]
bordercolor = [0, 0, 0, 0]

[CONFIRM_WINDOW_STRINGS]
string = [["profile_exists_confirm1", "font:interface_normal", "pos:{400", "228}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:1.10", "state:{CS}"], ["profile_exists_confirm2", "font:interface_normal", "pos:{400", "248}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:1.10", "state:{CS}"]]

[NOTE_WINDOW_FADER]
babsoluterectangle = 5
position = [0, 0, 800, 600]
leftcolor = [150, 50, 50, 0]
topcolor = [150, 50, 50, 0]
rightcolor = [150, 50, 50, 0]
bottomcolor = [150, 50, 50, 0]
bordercolor = [0, 0, 0, 0]

[NOTE_WINDOW_FRAME]
position = [190, 190, 610, 360]

[NOTE_WINDOW_TEXT]
babsoluterectangle = 5
position = [211, 203, 590, 309]
fontscale = 0.9
linespace = 20
glowoffset = [0, 0]
string = "NoteText_ProfileName_Incorrect"
valignment = 1

[NOTE_WINDOW_OK]
bbreakcommand = 1
command = [["activate", "event:noteOk"], ["click", "event:noteOk"]]
position = [329, 318, 469, 350]
string = "Ok"
glowoffset = [0, 0]

[NOTE_WINDOW]
show = 0
nodelist = ["NOTE_WINDOW_FADER", "NOTE_WINDOW_FRAME", "NOTE_WINDOW_TEXT", "NOTE_WINDOW_OK"]
