[MAIN]
item = ["PICTURE", "MAIN_BACK", "83", "PCEDITBOX", "EDITBOX_STRING", "200", "FORMATEDTEXT", "CAPTION_STRING", "200", "TEXTBUTTON2", "BTN_SEND"]
start = "EDITBOX_STRING"

[MAIN_BACK]
position = [0, 563, 800, 599]
texturename = "interfaces\\mainback.tga"

[CAPTION_STRING]
position = [6, 575, 136, 592]
fontscale = 0.9
linespace = 14
alignment = "left"
color = [255, 255, 255, 156]
string = "capNetCS_GameName"

[EDITBOX_STRING]
command = ["click", "select:EDITBOX_STRING", "deactivate", "event:OnCancel", "activate"]
position = [75, 569, 680, 596]
strfont = "interface_normal"
fontscale = 1.0
argbfontcolor = [255, 255, 255, 255]
stringlength = 100
stringoffset = [4, 7]
stringalign = "left"
middleimage = ["color=(255", "128", "128", "128)", "piclist=MAIN_ICONS", "picname=middle", "side", "button"]

[BTN_SEND]
bbreakcommand = 1
command = ["deactivate", "event:OnCancel", "click", "event:OnSend"]
position = [686, 566, 793, 598]
string = "btnChatString_Send"
glowoffset = [0, 0]
presspictureoffset = [2, 2]
