[MAIN]
item = ["501", "FRAME", "FRAME_ENDGAME", "502", "IMAGECOLLECTION", "BORDER_ENDGAME", "503", "FORMATEDTEXT", "TEXT_ENDGAME", "503", "STRINGCOLLECTION", "STRINGS_ENDGAME", "503", "TEXTBUTTON2", "BTN_ENDGAME_OK"]
start = "BTN_ENDGAME_OK"

[FRAME_ENDGAME]
position = [220, 184, 580, 360]

[BTN_ENDGAME_OK]
bbreakcommand = 1
command = ["click", "event:OnEndGameOk", "activate", "event:OnEndGameOk", "deactivate", "event:OnEndGameOk"]
position = [320, 313, 477, 345]
string = "btnEG_Ok"
glowoffset = [0, 0]
presspictureoffset = [2, 2]

[TEXT_ENDGAME]
position = [275, 240, 525, 300]
fontscale = 1.2
linespace = 14
alignment = "center"
color = [255, 255, 255, 156]

[BORDER_ENDGAME]
offset = [202, -170]
groupname = "MAIN_ICONS"
picture = ["SKILLBORDER", "col:{255", "128", "128", "128}", "pos:{224", "188", "577", "214}"]

[STRINGS_ENDGAME]
string = ["capEG_CapEndGame", "font:interface_button", "pos:{402", "190}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:1.00", "state:{CS}"]
