[MAIN]
item = [["501", "FRAME", "FRAME_NETMENU"], ["502", "IMAGECOLLECTION", "BORDER_NETMENU"], ["503", "FORMATEDTEXT", "TEXT_NETMENU"], ["503", "STRINGCOLLECTION", "STRINGS_NETMENU"], ["503", "TEXTBUTTON2", "BTN_NETMENU_DISCONNECT"], ["503", "TEXTBUTTON2", "BTN_ENDGAME_RETURN"]]
start = "BTN_ENDGAME_RETURN"

[FRAME_NETMENU]
position = [220, 184, 580, 360]

[BTN_NETMENU_DISCONNECT]
bbreakcommand = 1
command = [["click", "event:OnNetMenuDisconnect"], ["activate", "event:OnNetMenuDisconnect"], ["deactivate", "event:OnNetMenuReturn"]]
position = [300, 243, 497, 275]
string = "btnNM_Disconnect"
glowoffset = [0, 0]
presspictureoffset = [2, 2]

[BTN_ENDGAME_RETURN]
bbreakcommand = 1
command = [["click", "event:OnNetMenuReturn"], ["activate", "event:OnNetMenuReturn"], ["deactivate", "event:OnNetMenuReturn"]]
position = [300, 293, 497, 325]
string = "btnNM_Return"
glowoffset = [0, 0]
presspictureoffset = [2, 2]

[TEXT_NETMENU]
position = [235, 231, 565, 298]
fontscale = 1.0
linespace = 14
alignment = "center"
color = [255, 255, 255, 156]

[BORDER_NETMENU]
offset = [202, -170]
groupname = "MAIN_ICONS"
picture = ["SKILLBORDER", "col:{255", "128", "128", "128}", "pos:{224", "188", "577", "214}"]

[STRINGS_NETMENU]
string = ["capNM_CapNetMenu", "font:interface_button", "pos:{402", "190}", "fc:{255", "255", "255", "255}", "bc:{0", "128", "128", "128}", "scale:1.00", "state:{CS}"]
