[artifact]
technique = "particlesartifact"
emissiontime = 80
windeffect = 0
texture = "bluecorona.tga"
particles_num = 175
lifetime = 4700
emitradius = 20.5
psize_max = 0.004
psize_min = 0.0
ddeviation = 10
gravity = 0
initial_speed = 0.2
weight = [0.0, 0.0]
weight_deviation = 0.0
ptime = 0
pscale = 120.0
spin = [0.0, 10.0, 0.0, 1.0]
spin_deviation = 10.0
speed = [1.5, 2.0, 0.0009, 0.0, 0.0005, 900.0, -0.0002, 1200.0]
speed_deviation = 2
key_alpha = [1.0, 0.0, 0.7, 5000.0]
nonstopemit = [0, 0]
key_psize = [3.0, 0.0, 3.0, 1000.0, 0.2, 2200.0]
