[fort_smoke]
technique = "particles_inv"
emissiontime = 250
windeffect = [0.0025, 0.0, 0.0, 1.0, 50000.0]
key_windeffect = [0, 0]
nonstopemit = 0
texture = "smoke9.tga"
particles_num = 40
lifetime = 10000
emitradius = 1.0
psize_max = 0.02
psize_min = 0.0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 8000.0]
speed = [1.0, 0.0, 0.0, 0.0, 0.0002, 500.0, 0.002, 3000.0]
key_alpha = [0.0, 0.0, 0.0, 1500.0, 0.6, 3000.0, 0.0, 10000.0]
key_psize = [0, 0, 4, 3000, 7, 8000]

[fort_gray_smoke]
technique = "particles_inv"
nonstopemit = 0
emissiontime = 250
windeffect = [0.0025, 0.0, 0.0, 1.0, 50000.0]
texture = "smoke_gray.tga"
particles_num = 40
lifetime = 10000
emitradius = 1.0
psize_max = 0.02
psize_min = 0.0
ddeviation = 0.1
gravity = 0.0
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.0025, 1.0, 0.0, 0.1, 8000.0]
speed = [1.0, 0.0, 0.0, 0.0, 0.0002, 500.0, 0.002, 3000.0]
key_alpha = [0.0, 0.0, 0.0, 1500.0, 0.6, 3000.0, 0.0, 10000.0]
key_psize = [0, 0, 4, 3000, 7, 8000]

[fort_fire]
technique = "particles"
nonstopemit = 0
emissiontime = 100
windeffect = [0.0025, 0.0, 0.0, 1.0, 50000.0]
texture = "fire3.tga"
particles_num = 30
lifetime = 3000
emitradius = 2.0
psize_max = 0.02
psize_min = 0.0
ddeviation = 0.4
gravity = 0.0
initial_speed = 0.0
weight = [0.0, 0.0]
ptime = 0
pscale = 1.0
spin = [0.0, 0.0025, 0.3, 0.0, 0.1, 8000.0]
speed = [0.2, 0.0, 0.0, 0.0, 0.008, 3000.0]
key_alpha = [0.7, 0.0, 0.25, 2000.0, 0.0, 3000.0]
key_psize = [0, 0, 4, 3000, 8, 8000]
